/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatec.aula.view;

import br.edu.fatec.aula.dao.ClientesDAO;
import br.edu.fatec.aula.model.Clientes;
import java.awt.Color;
import java.awt.Cursor;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Tiago Guerino
 */
public class CadClienteInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadCarroInternalFrame
     */
    public CadClienteInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoButtonGroup = new javax.swing.ButtonGroup();
        principalPanel = new javax.swing.JPanel();
        pessoalPanel = new javax.swing.JPanel();
        nomeLabel = new javax.swing.JLabel();
        sexoLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        rgLabel = new javax.swing.JLabel();
        orgaoLabel = new javax.swing.JLabel();
        nascimentoLabel = new javax.swing.JLabel();
        civilLabel = new javax.swing.JLabel();
        orgaoTextField = new javax.swing.JTextField();
        nomeTextField = new javax.swing.JTextField();
        femininoRadioButton = new javax.swing.JRadioButton();
        masculinoRadioButton = new javax.swing.JRadioButton();
        rgFormattedTextField = new javax.swing.JFormattedTextField();
        cpfFormattedTextField = new javax.swing.JFormattedTextField();
        nascimentoFormattedTextField = new javax.swing.JFormattedTextField();
        civilComboBox = new javax.swing.JComboBox<>();
        contatoPanel = new javax.swing.JPanel();
        complementoLabel = new javax.swing.JLabel();
        enderecoLabel = new javax.swing.JLabel();
        cepLabel = new javax.swing.JLabel();
        cidadeLabel = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        bairroLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        telefoneLabel = new javax.swing.JLabel();
        celularLabel = new javax.swing.JLabel();
        enderecoTextField = new javax.swing.JTextField();
        cidadeTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        bairroTextField = new javax.swing.JTextField();
        cepFormattedTextField = new javax.swing.JFormattedTextField();
        telefoneFormattedTextField = new javax.swing.JFormattedTextField();
        celularFormattedTextField = new javax.swing.JFormattedTextField();
        estadoComboBox = new javax.swing.JComboBox<>();
        complementoTextField = new javax.swing.JTextField();
        profissionalPanel = new javax.swing.JPanel();
        ocupacaoLabel = new javax.swing.JLabel();
        salarioLabel = new javax.swing.JLabel();
        ocupacaoTextField = new javax.swing.JTextField();
        salarioFormattedTextField = new javax.swing.JFormattedTextField();
        enviarButtonPanel = new javax.swing.JPanel();
        enviarButtonLabel = new javax.swing.JLabel();
        limparButtonPanel = new javax.swing.JPanel();
        limparButtonLabel = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Clientes");
        setAutoscrolls(true);

        principalPanel.setBackground(new java.awt.Color(204, 0, 0));

        pessoalPanel.setBackground(new java.awt.Color(204, 0, 0));
        pessoalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Pessoal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 13), new java.awt.Color(255, 255, 204))); // NOI18N
        pessoalPanel.setForeground(new java.awt.Color(255, 255, 204));

        nomeLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(255, 255, 204));
        nomeLabel.setText("Nome");

        sexoLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        sexoLabel.setForeground(new java.awt.Color(255, 255, 204));
        sexoLabel.setText("Sexo");

        cpfLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cpfLabel.setForeground(new java.awt.Color(255, 255, 204));
        cpfLabel.setText("CPF");

        rgLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        rgLabel.setForeground(new java.awt.Color(255, 255, 204));
        rgLabel.setText("RG");

        orgaoLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        orgaoLabel.setForeground(new java.awt.Color(255, 255, 204));
        orgaoLabel.setText("Orgão emissor");

        nascimentoLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nascimentoLabel.setForeground(new java.awt.Color(255, 255, 204));
        nascimentoLabel.setText("Data nascimento");

        civilLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        civilLabel.setForeground(new java.awt.Color(255, 255, 204));
        civilLabel.setText("Estado civil");

        orgaoTextField.setBackground(new java.awt.Color(204, 0, 0));
        orgaoTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        orgaoTextField.setForeground(new java.awt.Color(255, 255, 204));
        orgaoTextField.setToolTipText("Orgão emissor do RG");
        orgaoTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        nomeTextField.setBackground(new java.awt.Color(204, 0, 0));
        nomeTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nomeTextField.setForeground(new java.awt.Color(255, 255, 204));
        nomeTextField.setToolTipText("Nome do cliente");
        nomeTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        femininoRadioButton.setBackground(new java.awt.Color(204, 0, 0));
        sexoButtonGroup.add(femininoRadioButton);
        femininoRadioButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        femininoRadioButton.setForeground(new java.awt.Color(255, 255, 204));
        femininoRadioButton.setSelected(true);
        femininoRadioButton.setText("Feminino");
        femininoRadioButton.setToolTipText("Sexo do cliente");

        masculinoRadioButton.setBackground(new java.awt.Color(204, 0, 0));
        sexoButtonGroup.add(masculinoRadioButton);
        masculinoRadioButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masculinoRadioButton.setForeground(new java.awt.Color(255, 255, 204));
        masculinoRadioButton.setText("Masculino");
        masculinoRadioButton.setToolTipText("Sexo do cliente");

        rgFormattedTextField.setBackground(new java.awt.Color(204, 0, 0));
        rgFormattedTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rgFormattedTextField.setForeground(new java.awt.Color(255, 255, 204));
        try {
            rgFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rgFormattedTextField.setToolTipText("RG do cliente");
        rgFormattedTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        cpfFormattedTextField.setBackground(new java.awt.Color(204, 0, 0));
        cpfFormattedTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cpfFormattedTextField.setForeground(new java.awt.Color(255, 255, 204));
        try {
            cpfFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfFormattedTextField.setToolTipText("CPF do cliente");
        cpfFormattedTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        nascimentoFormattedTextField.setBackground(new java.awt.Color(204, 0, 0));
        nascimentoFormattedTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nascimentoFormattedTextField.setForeground(new java.awt.Color(255, 255, 204));
        try {
            nascimentoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nascimentoFormattedTextField.setToolTipText("Data de nascimento do cliente");
        nascimentoFormattedTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        civilComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        civilComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Solteiro", "União estável", "Casado", "Separado", "Divorciado", "Viuvo" }));
        civilComboBox.setToolTipText("Estado civil do cliente");

        javax.swing.GroupLayout pessoalPanelLayout = new javax.swing.GroupLayout(pessoalPanel);
        pessoalPanel.setLayout(pessoalPanelLayout);
        pessoalPanelLayout.setHorizontalGroup(
            pessoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pessoalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pessoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pessoalPanelLayout.createSequentialGroup()
                        .addGroup(pessoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pessoalPanelLayout.createSequentialGroup()
                                .addComponent(civilLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(civilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pessoalPanelLayout.createSequentialGroup()
                                .addComponent(rgLabel)
                                .addGap(25, 25, 25)
                                .addComponent(rgFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(orgaoLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orgaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cpfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pessoalPanelLayout.createSequentialGroup()
                        .addGroup(pessoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pessoalPanelLayout.createSequentialGroup()
                                .addComponent(nomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pessoalPanelLayout.createSequentialGroup()
                                .addComponent(sexoLabel)
                                .addGap(18, 18, 18)
                                .addComponent(femininoRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(masculinoRadioButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nascimentoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nascimentoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pessoalPanelLayout.setVerticalGroup(
            pessoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pessoalPanelLayout.createSequentialGroup()
                .addGroup(pessoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nascimentoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nascimentoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pessoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(femininoRadioButton)
                    .addComponent(masculinoRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pessoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orgaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orgaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(pessoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(civilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(civilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        contatoPanel.setBackground(new java.awt.Color(204, 0, 0));
        contatoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 13), new java.awt.Color(255, 255, 204))); // NOI18N

        complementoLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        complementoLabel.setForeground(new java.awt.Color(255, 255, 204));
        complementoLabel.setText("Complemento");

        enderecoLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        enderecoLabel.setForeground(new java.awt.Color(255, 255, 204));
        enderecoLabel.setText("Endereço");

        cepLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cepLabel.setForeground(new java.awt.Color(255, 255, 204));
        cepLabel.setText("CEP");

        cidadeLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cidadeLabel.setForeground(new java.awt.Color(255, 255, 204));
        cidadeLabel.setText("Cidade");

        estadoLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        estadoLabel.setForeground(new java.awt.Color(255, 255, 204));
        estadoLabel.setText("Estado");

        bairroLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bairroLabel.setForeground(new java.awt.Color(255, 255, 204));
        bairroLabel.setText("Bairro");

        emailLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 204));
        emailLabel.setText("E-Mail");

        telefoneLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        telefoneLabel.setForeground(new java.awt.Color(255, 255, 204));
        telefoneLabel.setText("Telefone");

        celularLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        celularLabel.setForeground(new java.awt.Color(255, 255, 204));
        celularLabel.setText("Celular");

        enderecoTextField.setBackground(new java.awt.Color(204, 0, 0));
        enderecoTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        enderecoTextField.setForeground(new java.awt.Color(255, 255, 204));
        enderecoTextField.setToolTipText("Endereço do cliente");
        enderecoTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        cidadeTextField.setBackground(new java.awt.Color(204, 0, 0));
        cidadeTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cidadeTextField.setForeground(new java.awt.Color(255, 255, 204));
        cidadeTextField.setToolTipText("Cidade do cliente");
        cidadeTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        emailTextField.setBackground(new java.awt.Color(204, 0, 0));
        emailTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(255, 255, 204));
        emailTextField.setToolTipText("E-mail do cliente");
        emailTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        bairroTextField.setBackground(new java.awt.Color(204, 0, 0));
        bairroTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bairroTextField.setForeground(new java.awt.Color(255, 255, 204));
        bairroTextField.setToolTipText("Bairro do cliente");
        bairroTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        cepFormattedTextField.setBackground(new java.awt.Color(204, 0, 0));
        cepFormattedTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cepFormattedTextField.setForeground(new java.awt.Color(255, 255, 204));
        try {
            cepFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cepFormattedTextField.setToolTipText("CEP do cliente");
        cepFormattedTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        telefoneFormattedTextField.setBackground(new java.awt.Color(204, 0, 0));
        telefoneFormattedTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        telefoneFormattedTextField.setForeground(new java.awt.Color(255, 255, 204));
        try {
            telefoneFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneFormattedTextField.setToolTipText("Telefone fixo do cliente");
        telefoneFormattedTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        celularFormattedTextField.setBackground(new java.awt.Color(204, 0, 0));
        celularFormattedTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        celularFormattedTextField.setForeground(new java.awt.Color(255, 255, 204));
        try {
            celularFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        celularFormattedTextField.setToolTipText("Telefone celular do cliente");
        celularFormattedTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        estadoComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        estadoComboBox.setToolTipText("Estado  do cliente");

        complementoTextField.setBackground(new java.awt.Color(204, 0, 0));
        complementoTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        complementoTextField.setForeground(new java.awt.Color(255, 255, 204));
        complementoTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout contatoPanelLayout = new javax.swing.GroupLayout(contatoPanel);
        contatoPanel.setLayout(contatoPanelLayout);
        contatoPanelLayout.setHorizontalGroup(
            contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contatoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contatoPanelLayout.createSequentialGroup()
                        .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoLabel)
                            .addComponent(cidadeLabel)
                            .addComponent(bairroLabel)
                            .addComponent(telefoneLabel))
                        .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contatoPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enderecoTextField)
                                    .addComponent(cidadeTextField)
                                    .addComponent(bairroTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(contatoPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(telefoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contatoPanelLayout.createSequentialGroup()
                                .addComponent(celularLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(celularFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contatoPanelLayout.createSequentialGroup()
                                    .addComponent(estadoLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(estadoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contatoPanelLayout.createSequentialGroup()
                                    .addComponent(cepLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cepFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(contatoPanelLayout.createSequentialGroup()
                                .addComponent(complementoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(complementoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(contatoPanelLayout.createSequentialGroup()
                        .addComponent(emailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        contatoPanelLayout.setVerticalGroup(
            contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contatoPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complementoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complementoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cepLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bairroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cepFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celularLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celularFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        profissionalPanel.setBackground(new java.awt.Color(204, 0, 0));
        profissionalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Profissional", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 13), new java.awt.Color(255, 255, 204))); // NOI18N

        ocupacaoLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        ocupacaoLabel.setForeground(new java.awt.Color(255, 255, 204));
        ocupacaoLabel.setText("Ocupação");

        salarioLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        salarioLabel.setForeground(new java.awt.Color(255, 255, 204));
        salarioLabel.setText("Renda salarial");

        ocupacaoTextField.setBackground(new java.awt.Color(204, 0, 0));
        ocupacaoTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        ocupacaoTextField.setForeground(new java.awt.Color(255, 255, 204));
        ocupacaoTextField.setToolTipText("Ocupação do cliente");
        ocupacaoTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        salarioFormattedTextField.setBackground(new java.awt.Color(204, 0, 0));
        salarioFormattedTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        salarioFormattedTextField.setForeground(new java.awt.Color(255, 255, 204));
        salarioFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        salarioFormattedTextField.setToolTipText("Renda salarial  do cliente");
        salarioFormattedTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout profissionalPanelLayout = new javax.swing.GroupLayout(profissionalPanel);
        profissionalPanel.setLayout(profissionalPanelLayout);
        profissionalPanelLayout.setHorizontalGroup(
            profissionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profissionalPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(profissionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profissionalPanelLayout.createSequentialGroup()
                        .addComponent(salarioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salarioFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(profissionalPanelLayout.createSequentialGroup()
                        .addComponent(ocupacaoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ocupacaoTextField)))
                .addGap(228, 228, 228))
        );
        profissionalPanelLayout.setVerticalGroup(
            profissionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profissionalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profissionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ocupacaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ocupacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profissionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salarioFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        enviarButtonPanel.setBackground(new java.awt.Color(255, 0, 0));

        enviarButtonLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        enviarButtonLabel.setForeground(new java.awt.Color(255, 255, 204));
        enviarButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enviarButtonLabel.setText("Enviar");
        enviarButtonLabel.setToolTipText("Cadastrar cliente");
        enviarButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviarButtonLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enviarButtonLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enviarButtonLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout enviarButtonPanelLayout = new javax.swing.GroupLayout(enviarButtonPanel);
        enviarButtonPanel.setLayout(enviarButtonPanelLayout);
        enviarButtonPanelLayout.setHorizontalGroup(
            enviarButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enviarButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        enviarButtonPanelLayout.setVerticalGroup(
            enviarButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enviarButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        limparButtonPanel.setBackground(new java.awt.Color(255, 0, 0));

        limparButtonLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        limparButtonLabel.setForeground(new java.awt.Color(255, 255, 204));
        limparButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        limparButtonLabel.setText("Limpar");
        limparButtonLabel.setToolTipText("Limpar campos");
        limparButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limparButtonLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                limparButtonLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                limparButtonLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout limparButtonPanelLayout = new javax.swing.GroupLayout(limparButtonPanel);
        limparButtonPanel.setLayout(limparButtonPanelLayout);
        limparButtonPanelLayout.setHorizontalGroup(
            limparButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(limparButtonPanelLayout.createSequentialGroup()
                .addComponent(limparButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        limparButtonPanelLayout.setVerticalGroup(
            limparButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, limparButtonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(limparButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout principalPanelLayout = new javax.swing.GroupLayout(principalPanel);
        principalPanel.setLayout(principalPanelLayout);
        principalPanelLayout.setHorizontalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pessoalPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contatoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profissionalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createSequentialGroup()
                        .addComponent(limparButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enviarButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        principalPanelLayout.setVerticalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pessoalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contatoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profissionalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enviarButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void limpar() {
        nomeTextField.setText("");
        nascimentoFormattedTextField.setValue(null);
        femininoRadioButton.isSelected();
        rgFormattedTextField.setValue(null);
        orgaoTextField.setText("");
        cpfFormattedTextField.setValue(null);
        estadoComboBox.setSelectedIndex(0);
        civilComboBox.setSelectedIndex(0);
        enderecoTextField.setText("");
        complementoTextField.setText("");
        bairroTextField.setText("");
        cidadeTextField.setText("");
        cepFormattedTextField.setValue(null);
        telefoneFormattedTextField.setValue(null);
        celularFormattedTextField.setValue(null);
        emailTextField.setText("");
        ocupacaoTextField.setText("");
        salarioFormattedTextField.setValue(null);
    }
    private void limparButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparButtonLabelMouseClicked
        this.limpar();
    }//GEN-LAST:event_limparButtonLabelMouseClicked

    private void enviarButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarButtonLabelMouseClicked
        if (nomeTextField.getText().equals("")
                || nascimentoFormattedTextField.getText().equals("  /  /    ")
                || cpfFormattedTextField.getText().equals("   .   .   -  ")
                || rgFormattedTextField.getText().equals("  .   .   - ")
                || orgaoTextField.getText().equals("")
                || enderecoTextField.getText().equals("")
                || complementoTextField.getText().equals("")
                || bairroTextField.getText().equals("")
                || cepFormattedTextField.getText().equals("  .   -   ")
                || cidadeTextField.getText().equals("")
                || telefoneFormattedTextField.getText().equals("(  )     -    ")
                || celularFormattedTextField.getText().equals("(  )      -    ")
                || emailTextField.getText().equals("")
                || ocupacaoTextField.getText().equals("")
                || salarioFormattedTextField.getText().equals("")) {
            
            JOptionPane.showMessageDialog(this, "Campo vazio, insira valores");
            return;
        }
        if(civilComboBox.getSelectedItem().equals("Selecione")||estadoComboBox.getSelectedItem().equals("Selecione")){
            JOptionPane.showMessageDialog(this, "Escolha uma opção");
            return;
        }
        
        Clientes clientes = new Clientes();
        
        clientes.setBairro(bairroTextField.getText());
        clientes.setCelular(String.valueOf(celularFormattedTextField.getValue()));
        clientes.setCep(String.valueOf(cepFormattedTextField.getValue()));
        clientes.setCidade(cidadeTextField.getText());
        clientes.setCivil(String.valueOf(civilComboBox.getSelectedItem()));
        clientes.setComplemento(complementoTextField.getText());
        clientes.setCpf(String.valueOf(cpfFormattedTextField.getValue()));
        clientes.setEmail(emailTextField.getText());
        clientes.setEndereco(enderecoTextField.getText());
        clientes.setEstado(String.valueOf(estadoComboBox.getSelectedItem()));
        clientes.setNome(nomeTextField.getText());
        clientes.setOcupacao(ocupacaoTextField.getText());
        clientes.setOrgao(orgaoTextField.getText());
        clientes.setRg(String.valueOf(rgFormattedTextField.getValue()));
        clientes.setTelefone(String.valueOf(telefoneFormattedTextField.getValue()));
        
        if (femininoRadioButton.isSelected()) {
            clientes.setSexo(femininoRadioButton.getText());
        } else {
            clientes.setSexo(masculinoRadioButton.getText());
        }
        
        String s = salarioFormattedTextField.getText().replace(',', '.');
        Double salario = Double.parseDouble(s);
        clientes.setSalario(salario);
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date data = null;
        try {
            data = formato.parse(String.valueOf(nascimentoFormattedTextField.getValue()));
        } catch (ParseException ex) {
            Logger.getLogger(CadClienteInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        clientes.setNascimento(data);
        
        ClientesDAO clientesDAO = new ClientesDAO();
        clientesDAO.insere(clientes);
        
        JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso com o ID: "
                + clientes.getIdclientes());
        this.limpar();
    }//GEN-LAST:event_enviarButtonLabelMouseClicked

    private void limparButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparButtonLabelMouseEntered
        getContentPane().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        limparButtonPanel.setBackground(new Color(255, 23, 23));
    }//GEN-LAST:event_limparButtonLabelMouseEntered

    private void enviarButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarButtonLabelMouseEntered
        getContentPane().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        enviarButtonPanel.setBackground(new Color(255, 23, 23));
    }//GEN-LAST:event_enviarButtonLabelMouseEntered

    private void limparButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparButtonLabelMouseExited
        getContentPane().setCursor(Cursor.getDefaultCursor());
        limparButtonPanel.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_limparButtonLabelMouseExited

    private void enviarButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarButtonLabelMouseExited
        getContentPane().setCursor(Cursor.getDefaultCursor());
        enviarButtonPanel.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_enviarButtonLabelMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JTextField bairroTextField;
    private javax.swing.JFormattedTextField celularFormattedTextField;
    private javax.swing.JLabel celularLabel;
    private javax.swing.JFormattedTextField cepFormattedTextField;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JTextField cidadeTextField;
    private javax.swing.JComboBox<String> civilComboBox;
    private javax.swing.JLabel civilLabel;
    private javax.swing.JLabel complementoLabel;
    private javax.swing.JTextField complementoTextField;
    private javax.swing.JPanel contatoPanel;
    private javax.swing.JFormattedTextField cpfFormattedTextField;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JTextField enderecoTextField;
    private javax.swing.JLabel enviarButtonLabel;
    private javax.swing.JPanel enviarButtonPanel;
    private javax.swing.JComboBox<String> estadoComboBox;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JRadioButton femininoRadioButton;
    private javax.swing.JLabel limparButtonLabel;
    private javax.swing.JPanel limparButtonPanel;
    private javax.swing.JRadioButton masculinoRadioButton;
    private javax.swing.JFormattedTextField nascimentoFormattedTextField;
    private javax.swing.JLabel nascimentoLabel;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JLabel ocupacaoLabel;
    private javax.swing.JTextField ocupacaoTextField;
    private javax.swing.JLabel orgaoLabel;
    private javax.swing.JTextField orgaoTextField;
    private javax.swing.JPanel pessoalPanel;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JPanel profissionalPanel;
    private javax.swing.JFormattedTextField rgFormattedTextField;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JFormattedTextField salarioFormattedTextField;
    private javax.swing.JLabel salarioLabel;
    private javax.swing.ButtonGroup sexoButtonGroup;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JFormattedTextField telefoneFormattedTextField;
    private javax.swing.JLabel telefoneLabel;
    // End of variables declaration//GEN-END:variables
}
