/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatec.aula.view;

import br.edu.fatec.aula.dao.CarrosDAO;
import br.edu.fatec.aula.model.Carros;
import br.edu.fatec.aula.model.HibernateUtil;
import java.awt.Color;
import java.awt.Cursor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 *
 * @author Tiago Guerino
 */
public class ConsultaCarroInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaCarroInternalFrame
     */
    public ConsultaCarroInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void listaModelo() {
        Carros carro = new Carros();
        List<Carros> list = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

        try {
            session.beginTransaction();
            list = session.createQuery("select c from Carros c where modelo='"
                    + carro.getParametro() + "'").list();
            session.getTransaction().commit();

            for (Carros c : list) {
                DefaultTableModel tabela;
                tabela = (DefaultTableModel) tabelaCarroTable.getModel();
                Object[] linha = {
                    c.getIdcarros(),
                    c.getModelo(),
                    c.getMarca(),
                    c.getAno(),
                    c.getKm(),
                    c.getCor(),
                    c.getTipo(),
                    c.getCombustivel(),
                    c.getCilindradas(),
                    c.getValor(),
                    c.getOpcional(),};
                tabela.addRow(linha);
            }

        } catch (HibernateException e) {
            if (session.getTransaction() != null) {
                session.getTransaction().rollback();
            }
        } finally {
            session.close();
        }

    }

    public void listaMarca() {
        List<Carros> list = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

        try {
            Carros carro = new Carros();
            session.beginTransaction();
            list = session.createQuery("select c from Carros c where marca='"
                    + carro.getParametro() + "'").list();
            session.getTransaction().commit();

            for (Carros c : list) {
                DefaultTableModel tabela;
                tabela = (DefaultTableModel) tabelaCarroTable.getModel();
                Object[] linha = {
                    c.getIdcarros(),
                    c.getModelo(),
                    c.getMarca(),
                    c.getAno(),
                    c.getKm(),
                    c.getCor(),
                    c.getTipo(),
                    c.getCombustivel(),
                    c.getCilindradas(),
                    c.getValor(),
                    c.getOpcional(),};
                tabela.addRow(linha);

            }

        } catch (HibernateException e) {
            if (session.getTransaction() != null) {
                session.getTransaction().rollback();
            }
        } finally {
            session.close();
        }
    }

    public void listaAno() {
        List<Carros> list = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

        try {
            ConsultaCarroInternalFrame v = new ConsultaCarroInternalFrame();
            Carros carro = new Carros();
            session.beginTransaction();
            list = session.createQuery("select c from Carros c where ano='" + carro.getParametro() + "'").list();
            session.getTransaction().commit();

            for (Carros c : list) {
                DefaultTableModel tabela;
                tabela = (DefaultTableModel) tabelaCarroTable.getModel();
                Object[] linha = {
                    c.getIdcarros(),
                    c.getModelo(),
                    c.getMarca(),
                    c.getAno(),
                    c.getKm(),
                    c.getCor(),
                    c.getTipo(),
                    c.getCombustivel(),
                    c.getCilindradas(),
                    c.getValor(),
                    c.getOpcional(),};
                tabela.addRow(linha);
            }

        } catch (HibernateException e) {
            if (session.getTransaction() != null) {
                session.getTransaction().rollback();
            }
        } finally {
            session.close();
        }
    }
    
    public void listaTudo() {
        List<Carros> list = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

        try {
            Carros carro = new Carros();
            session.beginTransaction();
            list = session.createQuery("select c from Carros c").list();
            session.getTransaction().commit();

            for (Carros c : list) {
                DefaultTableModel tabela;
                tabela = (DefaultTableModel) tabelaCarroTable.getModel();
                Object[] linha = {
                    c.getIdcarros(),
                    c.getModelo(),
                    c.getMarca(),
                    c.getAno(),
                    c.getKm(),
                    c.getCor(),
                    c.getTipo(),
                    c.getCombustivel(),
                    c.getCilindradas(),
                    c.getValor(),
                    c.getOpcional(),};
                tabela.addRow(linha);

            }

        } catch (HibernateException e) {
            if (session.getTransaction() != null) {
                session.getTransaction().rollback();
            }
        } finally {
            session.close();
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscaPanel = new javax.swing.JPanel();
        marcaLabel = new javax.swing.JLabel();
        modeloLabel = new javax.swing.JLabel();
        anoLabel = new javax.swing.JLabel();
        modeloTextField = new javax.swing.JTextField();
        marcaTextField = new javax.swing.JTextField();
        anoTextField = new javax.swing.JTextField();
        buscarButtonPanel = new javax.swing.JPanel();
        buscarButtonLabel = new javax.swing.JLabel();
        limparButtonPanel = new javax.swing.JPanel();
        limparButtonLabel = new javax.swing.JLabel();
        veiculosPanel = new javax.swing.JPanel();
        tabelaCarroScrollPanel = new javax.swing.JScrollPane();
        tabelaCarroTable = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Consulta de Veículos");

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        buscaPanel.setBackground(new java.awt.Color(204, 0, 0));
        buscaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Busca de veículos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 13), new java.awt.Color(255, 255, 204))); // NOI18N

        marcaLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        marcaLabel.setForeground(new java.awt.Color(255, 255, 204));
        marcaLabel.setText("Marca");

        modeloLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        modeloLabel.setForeground(new java.awt.Color(255, 255, 204));
        modeloLabel.setText("Modelo");

        anoLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        anoLabel.setForeground(new java.awt.Color(255, 255, 204));
        anoLabel.setText("Ano");

        modeloTextField.setBackground(new java.awt.Color(204, 0, 0));
        modeloTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        modeloTextField.setForeground(new java.awt.Color(255, 255, 204));
        modeloTextField.setToolTipText("Modelo do veículo");
        modeloTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        marcaTextField.setBackground(new java.awt.Color(204, 0, 0));
        marcaTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        marcaTextField.setToolTipText("Marca do veículo");
        marcaTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        anoTextField.setBackground(new java.awt.Color(204, 0, 0));
        anoTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        anoTextField.setForeground(new java.awt.Color(255, 255, 204));
        anoTextField.setToolTipText("Ano do veículo");
        anoTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        buscarButtonPanel.setBackground(new java.awt.Color(255, 0, 0));

        buscarButtonLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        buscarButtonLabel.setForeground(new java.awt.Color(255, 255, 255));
        buscarButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscarButtonLabel.setText("Buscar");
        buscarButtonLabel.setToolTipText("Buscar veículo");
        buscarButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarButtonLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarButtonLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarButtonLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buscarButtonPanelLayout = new javax.swing.GroupLayout(buscarButtonPanel);
        buscarButtonPanel.setLayout(buscarButtonPanelLayout);
        buscarButtonPanelLayout.setHorizontalGroup(
            buscarButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        buscarButtonPanelLayout.setVerticalGroup(
            buscarButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        limparButtonPanel.setBackground(new java.awt.Color(255, 0, 0));

        limparButtonLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        limparButtonLabel.setForeground(new java.awt.Color(255, 255, 255));
        limparButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        limparButtonLabel.setText("Limpar Busca");
        limparButtonLabel.setToolTipText("Buscar veículo");
        limparButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limparButtonLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                limparButtonLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                limparButtonLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout limparButtonPanelLayout = new javax.swing.GroupLayout(limparButtonPanel);
        limparButtonPanel.setLayout(limparButtonPanelLayout);
        limparButtonPanelLayout.setHorizontalGroup(
            limparButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(limparButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        limparButtonPanelLayout.setVerticalGroup(
            limparButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(limparButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout buscaPanelLayout = new javax.swing.GroupLayout(buscaPanel);
        buscaPanel.setLayout(buscaPanelLayout);
        buscaPanelLayout.setHorizontalGroup(
            buscaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(buscaPanelLayout.createSequentialGroup()
                        .addComponent(modeloLabel)
                        .addGap(18, 18, 18)
                        .addComponent(modeloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buscaPanelLayout.createSequentialGroup()
                        .addComponent(anoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(anoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buscaPanelLayout.createSequentialGroup()
                        .addComponent(marcaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(marcaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(buscaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limparButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        buscaPanelLayout.setVerticalGroup(
            buscaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(buscaPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(buscaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buscaPanelLayout.createSequentialGroup()
                        .addComponent(buscarButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(limparButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buscaPanelLayout.createSequentialGroup()
                        .addGroup(buscaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modeloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modeloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(buscaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(anoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(buscaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marcaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marcaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12))
        );

        veiculosPanel.setBackground(new java.awt.Color(204, 0, 0));
        veiculosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Veículos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 13), new java.awt.Color(255, 255, 204))); // NOI18N
        veiculosPanel.setToolTipText("Dados do veículo");

        tabelaCarroScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        tabelaCarroScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        tabelaCarroScrollPanel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        tabelaCarroTable.setAutoCreateRowSorter(true);
        tabelaCarroTable.setBackground(new java.awt.Color(255, 51, 51));
        tabelaCarroTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tabelaCarroTable.setForeground(new java.awt.Color(255, 255, 204));
        tabelaCarroTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Modelo", "Marca", "Ano", "Kilometragem", "Cor", "Tipo", "Combustivel", "Motor", "Valor", "Opcionais"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCarroTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaCarroTable.setGridColor(new java.awt.Color(255, 102, 102));
        tabelaCarroTable.setSelectionBackground(new java.awt.Color(193, 21, 21));
        tabelaCarroTable.setSelectionForeground(new java.awt.Color(255, 255, 204));
        tabelaCarroScrollPanel.setViewportView(tabelaCarroTable);

        javax.swing.GroupLayout veiculosPanelLayout = new javax.swing.GroupLayout(veiculosPanel);
        veiculosPanel.setLayout(veiculosPanelLayout);
        veiculosPanelLayout.setHorizontalGroup(
            veiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(veiculosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelaCarroScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
        veiculosPanelLayout.setVerticalGroup(
            veiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaCarroScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(veiculosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(buscaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(veiculosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(buscaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(253, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarButtonLabelMouseClicked

        if (modeloTextField.getText().equals("")
                && marcaTextField.getText().equals("")
                && anoTextField.getText().equals("")) {
            this.listaTudo();
            return;
        }
        if (!marcaTextField.getText().equals("")) {
            this.listaMarca();

        }
        if (!modeloTextField.getText().equals("")) {
            this.listaModelo();

        }
        if (!anoTextField.getText().equals("")) {
            this.listaAno();

        }

    }//GEN-LAST:event_buscarButtonLabelMouseClicked

    private void limparButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparButtonLabelMouseClicked

        DefaultTableModel tabela;
        tabela = (DefaultTableModel) tabelaCarroTable.getModel();

        if (tabela.getRowCount() > 0) {
            while (tabela.getRowCount() > 0) {
                tabela.removeRow(0);
            }
        }
    }//GEN-LAST:event_limparButtonLabelMouseClicked

    private void buscarButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarButtonLabelMouseEntered
        getContentPane().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        buscarButtonPanel.setBackground(new Color(255,23,23));
    }//GEN-LAST:event_buscarButtonLabelMouseEntered

    private void limparButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparButtonLabelMouseEntered
        getContentPane().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        limparButtonPanel.setBackground(new Color(255,23,23));
    }//GEN-LAST:event_limparButtonLabelMouseEntered

    private void buscarButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarButtonLabelMouseExited
        getContentPane().setCursor(Cursor.getDefaultCursor());
        buscarButtonPanel.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_buscarButtonLabelMouseExited

    private void limparButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparButtonLabelMouseExited
        getContentPane().setCursor(Cursor.getDefaultCursor());
        limparButtonPanel.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_limparButtonLabelMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anoLabel;
    private javax.swing.JTextField anoTextField;
    private javax.swing.JPanel buscaPanel;
    private javax.swing.JLabel buscarButtonLabel;
    private javax.swing.JPanel buscarButtonPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel limparButtonLabel;
    private javax.swing.JPanel limparButtonPanel;
    private javax.swing.JLabel marcaLabel;
    private javax.swing.JTextField marcaTextField;
    private javax.swing.JLabel modeloLabel;
    private javax.swing.JTextField modeloTextField;
    private javax.swing.JScrollPane tabelaCarroScrollPanel;
    private javax.swing.JTable tabelaCarroTable;
    private javax.swing.JPanel veiculosPanel;
    // End of variables declaration//GEN-END:variables
}
