/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatec.aula.view;

import br.edu.fatec.aula.model.Login;
import br.edu.fatec.aula.model.HibernateUtil;
import java.awt.Color;
import java.awt.Cursor;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.SQLQuery;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Tiago Guerino
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        imgLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        fecharButtonPanel = new javax.swing.JPanel();
        fecharButtonLabel = new javax.swing.JLabel();
        loginButtonPanel = new javax.swing.JPanel();
        loginButtonLabel = new javax.swing.JLabel();
        usuarioLabel = new javax.swing.JLabel();
        senhaLabel = new javax.swing.JLabel();
        senhaPasswordField = new javax.swing.JPasswordField();
        usuarioTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendas de carros");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        principalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoPanel.setBackground(new java.awt.Color(255, 0, 0));

        imgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/aula/image/car-23-128.png"))); // NOI18N

        logoLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 204));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setText("Vendas de carros");

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(imgLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        principalPanel.add(logoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 370));

        loginPanel.setBackground(new java.awt.Color(204, 0, 0));

        fecharButtonPanel.setBackground(new java.awt.Color(255, 0, 0));
        fecharButtonPanel.setPreferredSize(new java.awt.Dimension(32, 32));

        fecharButtonLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        fecharButtonLabel.setForeground(new java.awt.Color(255, 255, 204));
        fecharButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecharButtonLabel.setText("X");
        fecharButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fecharButtonLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fecharButtonLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fecharButtonLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fecharButtonPanelLayout = new javax.swing.GroupLayout(fecharButtonPanel);
        fecharButtonPanel.setLayout(fecharButtonPanelLayout);
        fecharButtonPanelLayout.setHorizontalGroup(
            fecharButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fecharButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );
        fecharButtonPanelLayout.setVerticalGroup(
            fecharButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fecharButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        loginButtonPanel.setBackground(new java.awt.Color(255, 0, 0));

        loginButtonLabel.setBackground(new java.awt.Color(255, 0, 0));
        loginButtonLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginButtonLabel.setForeground(new java.awt.Color(255, 255, 204));
        loginButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginButtonLabel.setText("Entrar");
        loginButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginButtonPanelLayout = new javax.swing.GroupLayout(loginButtonPanel);
        loginButtonPanel.setLayout(loginButtonPanelLayout);
        loginButtonPanelLayout.setHorizontalGroup(
            loginButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        loginButtonPanelLayout.setVerticalGroup(
            loginButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        usuarioLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        usuarioLabel.setForeground(new java.awt.Color(255, 255, 204));
        usuarioLabel.setText("Usuário");

        senhaLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        senhaLabel.setForeground(new java.awt.Color(255, 255, 204));
        senhaLabel.setText("Senha");

        senhaPasswordField.setBackground(new java.awt.Color(204, 0, 0));
        senhaPasswordField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        senhaPasswordField.setForeground(new java.awt.Color(255, 255, 204));
        senhaPasswordField.setText("senhadousuario");
        senhaPasswordField.setBorder(null);
        senhaPasswordField.setEchoChar('\u2022');
        senhaPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhaPasswordFieldFocusGained(evt);
            }
        });

        usuarioTextField.setBackground(new java.awt.Color(204, 0, 0));
        usuarioTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        usuarioTextField.setForeground(new java.awt.Color(255, 255, 204));
        usuarioTextField.setText("Nome do usuário");
        usuarioTextField.setBorder(null);
        usuarioTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuarioTextFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fecharButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(loginButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(senhaPasswordField)
                    .addComponent(jSeparator2)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhaLabel))
                        .addGap(0, 234, Short.MAX_VALUE)))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(fecharButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(usuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(senhaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(loginButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        principalPanel.add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 320, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fecharButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharButtonLabelMouseClicked
        dispose();
    }//GEN-LAST:event_fecharButtonLabelMouseClicked

    private void senhaPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaPasswordFieldFocusGained
        senhaPasswordField.setText("");
    }//GEN-LAST:event_senhaPasswordFieldFocusGained

    private void usuarioTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioTextFieldFocusGained
        usuarioTextField.setText("");
    }//GEN-LAST:event_usuarioTextFieldFocusGained

    private void fecharButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharButtonLabelMouseEntered
        getContentPane().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        fecharButtonPanel.setBackground(new Color(255,23,23));
    }//GEN-LAST:event_fecharButtonLabelMouseEntered

    private void fecharButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharButtonLabelMouseExited
        getContentPane().setCursor(Cursor.getDefaultCursor());
        fecharButtonPanel.setBackground(Color.red);
    }//GEN-LAST:event_fecharButtonLabelMouseExited

    private void loginButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonLabelMouseEntered
        getContentPane().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        loginButtonPanel.setBackground(new Color(255, 23, 23));
    }//GEN-LAST:event_loginButtonLabelMouseEntered

    private void loginButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonLabelMouseExited
        getContentPane().setCursor(Cursor.getDefaultCursor());
        loginButtonPanel.setBackground(Color.red);
    }//GEN-LAST:event_loginButtonLabelMouseExited

    private void loginButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonLabelMouseClicked
        String usuario = usuarioTextField.getText();
        String senha = String.valueOf(senhaPasswordField.getPassword());

        Session banco = HibernateUtil.getSessionFactory().openSession();

        Transaction t = banco.beginTransaction();

        SQLQuery consulta = banco.createSQLQuery("SELECT * FROM login");
        consulta.addEntity(Login.class);

        List<Login> usuarios = (List<Login>) consulta.list();

        boolean logado=false;
        for (Login u : usuarios) {
            if (usuario.equals(u.getUsuario())&& senha.equals(u.getSenha())){
                logado = true;
                PrincipalFrame tela = new PrincipalFrame();
                tela.setVisible(true);
                dispose();
            }
        }
        if(!logado){
            JOptionPane.showMessageDialog(this, "Usuário ou senha inválidos");
        }
        
        banco.close();
    }//GEN-LAST:event_loginButtonLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fecharButtonLabel;
    private javax.swing.JPanel fecharButtonPanel;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel loginButtonLabel;
    private javax.swing.JPanel loginButtonPanel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JLabel usuarioLabel;
    private javax.swing.JTextField usuarioTextField;
    // End of variables declaration//GEN-END:variables
}
