/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatec.aula.view;

import br.edu.fatec.aula.dao.VendasDAO;
import br.edu.fatec.aula.model.Carros;
import br.edu.fatec.aula.model.Clientes;
import br.edu.fatec.aula.model.HibernateUtil;
import br.edu.fatec.aula.model.Venda;
import br.edu.fatec.aula.model.VendaId;
import java.awt.Color;
import java.awt.Cursor;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 *
 * @author Tiago Guerino
 */
public class VendasInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form VendasInternalFrame
     */
    public VendasInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void consultaCarro() {
        List<Carros> list = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

        try {
            session.beginTransaction();
            list = session.createQuery("select c from Carros c where idcarros='"
                    + codigoVeiculoFormattedTextField.getText() + "'").list();
            session.getTransaction().commit();

            for (Carros v : list) {
                modeloLabel.setText(v.getModelo());
                marcaLabel.setText(v.getMarca());
                anoLabel.setText(v.getAno());
                kmLabel.setText(v.getKm());
                valorLabel.setText(String.valueOf(v.getValor()));
            }
        } catch (HibernateException e) {
            if (session.getTransaction() != null) {
                session.getTransaction().rollback();
            }
        } finally {
            session.close();
        }

    }

    private void consultaCliente() {
        List<Clientes> list = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

        try {
            session.beginTransaction();
            list = session.createQuery("select c from Clientes c where idclientes='"
                    + codigoClienteFormattedTextField.getText() + "'").list();
            session.getTransaction().commit();

            for (Clientes c : list) {
                nomeLabel.setText(c.getNome());
                cpfLabel.setText(c.getCpf());
                rgLabel.setText(c.getRg() + " " + c.getOrgao());
            }
        } catch (HibernateException e) {
            if (session.getTransaction() != null) {
                session.getTransaction().rollback();
            }
        } finally {
            session.close();
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoPanel = new javax.swing.JPanel();
        valorPanel = new javax.swing.JPanel();
        parcelasLabel = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        parcelasComboBox = new javax.swing.JComboBox<>();
        entradaCheckBox = new javax.swing.JCheckBox();
        entradaFormattedTextField = new javax.swing.JFormattedTextField();
        totalLabel = new javax.swing.JLabel();
        calcularButtonPanel = new javax.swing.JPanel();
        calcularButtonLabel = new javax.swing.JLabel();
        salvarButtonPanel = new javax.swing.JPanel();
        salvarButtonLabel = new javax.swing.JLabel();
        veiculoPanel = new javax.swing.JPanel();
        modeloLabel = new javax.swing.JLabel();
        marcaLabel = new javax.swing.JLabel();
        anoLabel = new javax.swing.JLabel();
        corLabel = new javax.swing.JLabel();
        kmLabel = new javax.swing.JLabel();
        codigoVeiculoFormattedTextField = new javax.swing.JFormattedTextField();
        veiculoButtonPanel = new javax.swing.JPanel();
        veiculoButtonLabel = new javax.swing.JLabel();
        clientePanel = new javax.swing.JPanel();
        nomeLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        rgLabel = new javax.swing.JLabel();
        codigoClienteFormattedTextField = new javax.swing.JFormattedTextField();
        clienteButtonPanel = new javax.swing.JPanel();
        clienteButtonLabel = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Vendas");

        fundoPanel.setBackground(new java.awt.Color(204, 0, 0));

        valorPanel.setBackground(new java.awt.Color(204, 0, 0));
        valorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 14), new java.awt.Color(255, 255, 204))); // NOI18N

        parcelasLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        parcelasLabel.setForeground(new java.awt.Color(255, 255, 204));
        parcelasLabel.setText("Parcelas");

        valorLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        valorLabel.setForeground(new java.awt.Color(255, 255, 204));

        parcelasComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        parcelasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "18", "24", "30", "36", "42", "48", "54", "60" }));

        entradaCheckBox.setBackground(new java.awt.Color(204, 0, 0));
        entradaCheckBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        entradaCheckBox.setForeground(new java.awt.Color(255, 255, 204));
        entradaCheckBox.setText("Entrada");
        entradaCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                entradaCheckBoxItemStateChanged(evt);
            }
        });

        entradaFormattedTextField.setEditable(false);
        entradaFormattedTextField.setBackground(new java.awt.Color(204, 0, 0));
        entradaFormattedTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        entradaFormattedTextField.setForeground(new java.awt.Color(255, 255, 204));
        entradaFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        entradaFormattedTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        totalLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(255, 255, 204));

        calcularButtonPanel.setBackground(new java.awt.Color(255, 0, 0));
        calcularButtonPanel.setPreferredSize(new java.awt.Dimension(124, 42));

        calcularButtonLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        calcularButtonLabel.setForeground(new java.awt.Color(255, 255, 204));
        calcularButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calcularButtonLabel.setText("Calcular");
        calcularButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcularButtonLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calcularButtonLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calcularButtonLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout calcularButtonPanelLayout = new javax.swing.GroupLayout(calcularButtonPanel);
        calcularButtonPanel.setLayout(calcularButtonPanelLayout);
        calcularButtonPanelLayout.setHorizontalGroup(
            calcularButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calcularButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        calcularButtonPanelLayout.setVerticalGroup(
            calcularButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calcularButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        salvarButtonPanel.setBackground(new java.awt.Color(255, 0, 0));

        salvarButtonLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        salvarButtonLabel.setForeground(new java.awt.Color(255, 255, 204));
        salvarButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salvarButtonLabel.setText("Gerar Recibo");
        salvarButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarButtonLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salvarButtonLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salvarButtonLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout salvarButtonPanelLayout = new javax.swing.GroupLayout(salvarButtonPanel);
        salvarButtonPanel.setLayout(salvarButtonPanelLayout);
        salvarButtonPanelLayout.setHorizontalGroup(
            salvarButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salvarButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        salvarButtonPanelLayout.setVerticalGroup(
            salvarButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salvarButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout valorPanelLayout = new javax.swing.GroupLayout(valorPanel);
        valorPanel.setLayout(valorPanelLayout);
        valorPanelLayout.setHorizontalGroup(
            valorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(valorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(valorPanelLayout.createSequentialGroup()
                        .addGroup(valorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(valorPanelLayout.createSequentialGroup()
                                .addComponent(entradaCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(entradaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(valorPanelLayout.createSequentialGroup()
                                .addComponent(valorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(parcelasLabel)
                                .addGap(18, 18, 18)
                                .addComponent(parcelasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(valorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salvarButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcularButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        valorPanelLayout.setVerticalGroup(
            valorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, valorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(valorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calcularButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(valorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(parcelasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(parcelasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(valorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(valorPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(valorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entradaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(valorPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(salvarButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );

        veiculoPanel.setBackground(new java.awt.Color(204, 0, 0));
        veiculoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Código do Veículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 14), new java.awt.Color(255, 255, 204))); // NOI18N

        modeloLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        modeloLabel.setForeground(new java.awt.Color(255, 255, 204));

        marcaLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        marcaLabel.setForeground(new java.awt.Color(255, 255, 204));

        anoLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        anoLabel.setForeground(new java.awt.Color(255, 255, 204));

        corLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        corLabel.setForeground(new java.awt.Color(255, 255, 204));

        kmLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        kmLabel.setForeground(new java.awt.Color(255, 255, 204));

        codigoVeiculoFormattedTextField.setBackground(new java.awt.Color(204, 0, 0));
        codigoVeiculoFormattedTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        codigoVeiculoFormattedTextField.setForeground(new java.awt.Color(255, 255, 204));
        codigoVeiculoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        codigoVeiculoFormattedTextField.setToolTipText("Código do veículo");
        codigoVeiculoFormattedTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        veiculoButtonPanel.setBackground(new java.awt.Color(255, 0, 0));
        veiculoButtonPanel.setPreferredSize(new java.awt.Dimension(124, 42));

        veiculoButtonLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        veiculoButtonLabel.setForeground(new java.awt.Color(255, 255, 204));
        veiculoButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        veiculoButtonLabel.setText("Buscar veículo");
        veiculoButtonLabel.setToolTipText("Busca veículo");
        veiculoButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                veiculoButtonLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                veiculoButtonLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                veiculoButtonLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout veiculoButtonPanelLayout = new javax.swing.GroupLayout(veiculoButtonPanel);
        veiculoButtonPanel.setLayout(veiculoButtonPanelLayout);
        veiculoButtonPanelLayout.setHorizontalGroup(
            veiculoButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(veiculoButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        veiculoButtonPanelLayout.setVerticalGroup(
            veiculoButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(veiculoButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout veiculoPanelLayout = new javax.swing.GroupLayout(veiculoPanel);
        veiculoPanel.setLayout(veiculoPanelLayout);
        veiculoPanelLayout.setHorizontalGroup(
            veiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(veiculoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(veiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(veiculoPanelLayout.createSequentialGroup()
                        .addGroup(veiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modeloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(veiculoPanelLayout.createSequentialGroup()
                                .addComponent(anoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(corLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(92, 92, 92)
                        .addGroup(veiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(marcaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(veiculoPanelLayout.createSequentialGroup()
                        .addComponent(codigoVeiculoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(veiculoButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        veiculoPanelLayout.setVerticalGroup(
            veiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(veiculoPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(veiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoVeiculoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veiculoButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(veiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marcaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(veiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(corLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clientePanel.setBackground(new java.awt.Color(204, 0, 0));
        clientePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Código do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 14), new java.awt.Color(255, 255, 204))); // NOI18N

        nomeLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(255, 255, 204));
        nomeLabel.setToolTipText("Nome do cliente");

        cpfLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cpfLabel.setForeground(new java.awt.Color(255, 255, 204));

        rgLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        rgLabel.setForeground(new java.awt.Color(255, 255, 204));
        rgLabel.setToolTipText("");

        codigoClienteFormattedTextField.setBackground(new java.awt.Color(204, 0, 0));
        codigoClienteFormattedTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        codigoClienteFormattedTextField.setForeground(new java.awt.Color(255, 255, 204));
        codigoClienteFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        codigoClienteFormattedTextField.setToolTipText("Codigo do cliente");
        codigoClienteFormattedTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        codigoClienteFormattedTextField.setSelectedTextColor(new java.awt.Color(255, 255, 204));

        clienteButtonPanel.setBackground(new java.awt.Color(255, 0, 0));
        clienteButtonPanel.setPreferredSize(new java.awt.Dimension(124, 42));

        clienteButtonLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        clienteButtonLabel.setForeground(new java.awt.Color(255, 255, 204));
        clienteButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clienteButtonLabel.setText("Buscar cliente");
        clienteButtonLabel.setToolTipText("Busca cliente");
        clienteButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteButtonLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clienteButtonLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clienteButtonLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout clienteButtonPanelLayout = new javax.swing.GroupLayout(clienteButtonPanel);
        clienteButtonPanel.setLayout(clienteButtonPanelLayout);
        clienteButtonPanelLayout.setHorizontalGroup(
            clienteButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clienteButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        clienteButtonPanelLayout.setVerticalGroup(
            clienteButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clienteButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout clientePanelLayout = new javax.swing.GroupLayout(clientePanel);
        clientePanel.setLayout(clientePanelLayout);
        clientePanelLayout.setHorizontalGroup(
            clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(clientePanelLayout.createSequentialGroup()
                        .addComponent(cpfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(clientePanelLayout.createSequentialGroup()
                        .addComponent(codigoClienteFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clienteButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        clientePanelLayout.setVerticalGroup(
            clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clienteButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoClienteFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fundoPanelLayout = new javax.swing.GroupLayout(fundoPanel);
        fundoPanel.setLayout(fundoPanelLayout);
        fundoPanelLayout.setHorizontalGroup(
            fundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(valorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(clientePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(veiculoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fundoPanelLayout.setVerticalGroup(
            fundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(veiculoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(valorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entradaCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_entradaCheckBoxItemStateChanged

        if (entradaCheckBox.isSelected()) {
            entradaFormattedTextField.setEditable(true);
            entradaFormattedTextField.setBackground(new Color(204, 0, 0));
        } else {
            entradaFormattedTextField.setEditable(false);
        }
    }//GEN-LAST:event_entradaCheckBoxItemStateChanged

    private void salvarButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarButtonLabelMouseClicked
        DecimalFormat dfValor = new DecimalFormat("#0.00");
        Double entrada;

        if (!entradaCheckBox.isSelected()) {
            entrada = 0.0;
        } else {
            String e = entradaFormattedTextField.getText().replace(',', '.');
            entrada = Double.parseDouble(e);

        }

        List<Clientes> list = null;
        List<Carros> list2 = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.beginTransaction();
            list = session.createQuery("select c from Clientes c where idclientes='"
                    + codigoClienteFormattedTextField.getText() + "'").list();
            list2 = session.createQuery("select c from Carros c where idcarros='"
                    + codigoVeiculoFormattedTextField.getText() + "'").list();
            session.getTransaction().commit();

            for (Clientes c : list) {
                for (Carros v : list2) {

                    File arquivo = new File("Contrato - " + c.getNome() + "-" + v.getModelo() + ".doc");
                    FileWriter escritor = new FileWriter(arquivo);
                    BufferedWriter buffer = new BufferedWriter(escritor);

                    buffer.append("Recibo de Veiculo \n\n");
                    buffer.append("Comprador ");
                    buffer.append(c.getNome());
                    buffer.append(", portador do CPF ");
                    buffer.append(c.getCpf());
                    buffer.append(", e do RG ");
                    buffer.append(c.getRg());
                    buffer.append(", ");
                    buffer.append(c.getCivil());
                    buffer.append(", residente no endereço ");
                    buffer.append(c.getEndereco());
                    buffer.append(" CEP ");
                    buffer.append(c.getCep());
                    buffer.append(" bairro ");
                    buffer.append(c.getBairro());
                    buffer.append(" na cidade ");
                    buffer.append(c.getCidade());
                    buffer.append("/");
                    buffer.append(c.getEstado());
                    buffer.append(" comprou o veículo ");
                    buffer.append(v.getTipo());
                    buffer.append(" modelo ");
                    buffer.append(v.getModelo());
                    buffer.append(" da marca ");
                    buffer.append(v.getMarca());
                    buffer.append(" ano ");
                    buffer.append(v.getAno());
                    buffer.append(" cor ");
                    buffer.append(v.getCor());
                    buffer.append(" com ");
                    buffer.append(v.getKm());
                    buffer.append(" KM rodados, com");
                    buffer.append(totalLabel.getText());
                    buffer.append("\n\n\n\n");
                    buffer.append("Assinatura");

                    for (int i = 0; i < c.getNome().length(); i++) {
                        buffer.append("_");
                    }

                    buffer.append("\n\n");
                    buffer.append(c.getNome());
                    buffer.append("\n");
                    buffer.append(c.getTelefone());
                    buffer.append("\n");
                    buffer.append(c.getCelular());
                    buffer.append("\n");
                    buffer.append(c.getEmail());
                    buffer.append("\n");

                    buffer.close();
                    escritor.close();

                }

            }

        } catch (IOException ex) {
            Logger.getLogger(VendasInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HibernateException e) {
            if (session.getTransaction() != null) {
                session.getTransaction().rollback();
            }
        } finally {
            session.close();
        }


    }//GEN-LAST:event_salvarButtonLabelMouseClicked

    private void veiculoButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veiculoButtonLabelMouseClicked
         if(codigoVeiculoFormattedTextField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Insira o Id do carro");
        }else{
            this.consultaCarro();
        }
    }//GEN-LAST:event_veiculoButtonLabelMouseClicked

    private void clienteButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteButtonLabelMouseClicked
        if(codigoClienteFormattedTextField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Insira o Id do cliente");
        }else{
            this.consultaCliente();
        }
        

    }//GEN-LAST:event_clienteButtonLabelMouseClicked

    private void calcularButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularButtonLabelMouseClicked
        DecimalFormat dfValor = new DecimalFormat("#0.00");

        Double valor;
        Double parcelas;
        Double entrada;

        parcelas = Double.parseDouble(String.valueOf(parcelasComboBox.getSelectedItem()));
        valor = Double.parseDouble(valorLabel.getText());

        if (parcelasComboBox.getSelectedItem().equals("Selecione")) {
            JOptionPane.showMessageDialog(this, "Selecione a quantidade de parcelas");
            return;
        }

        if (!entradaCheckBox.isSelected()) {
            entrada = 0.0;
        } else {
            String e = entradaFormattedTextField.getText().replace(',', '.');
            entrada = Double.parseDouble(e);

        }

        Double total = (valor - entrada) / parcelas;

        totalLabel.setText("R$" + entradaFormattedTextField.getText() + " + "
                + String.valueOf(parcelasComboBox.getSelectedItem())
                + " x R$" + String.valueOf(dfValor.format(total)));
    }//GEN-LAST:event_calcularButtonLabelMouseClicked

    private void clienteButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteButtonLabelMouseEntered
        getContentPane().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        clienteButtonPanel.setBackground(new Color(255, 23, 23));
    }//GEN-LAST:event_clienteButtonLabelMouseEntered

    private void veiculoButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veiculoButtonLabelMouseEntered
        getContentPane().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        veiculoButtonPanel.setBackground(new Color(255, 23, 23));
    }//GEN-LAST:event_veiculoButtonLabelMouseEntered

    private void calcularButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularButtonLabelMouseEntered
        getContentPane().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        calcularButtonPanel.setBackground(new Color(255, 23, 23));
    }//GEN-LAST:event_calcularButtonLabelMouseEntered

    private void salvarButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarButtonLabelMouseEntered
        getContentPane().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        salvarButtonPanel.setBackground(new Color(255, 23, 23));
    }//GEN-LAST:event_salvarButtonLabelMouseEntered

    private void clienteButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteButtonLabelMouseExited
        getContentPane().setCursor(Cursor.getDefaultCursor());
        clienteButtonPanel.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_clienteButtonLabelMouseExited

    private void veiculoButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veiculoButtonLabelMouseExited
        getContentPane().setCursor(Cursor.getDefaultCursor());
        veiculoButtonPanel.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_veiculoButtonLabelMouseExited

    private void calcularButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularButtonLabelMouseExited
        getContentPane().setCursor(Cursor.getDefaultCursor());
        calcularButtonPanel.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_calcularButtonLabelMouseExited

    private void salvarButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarButtonLabelMouseExited
        getContentPane().setCursor(Cursor.getDefaultCursor());
        salvarButtonPanel.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_salvarButtonLabelMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anoLabel;
    private javax.swing.JLabel calcularButtonLabel;
    private javax.swing.JPanel calcularButtonPanel;
    private javax.swing.JLabel clienteButtonLabel;
    private javax.swing.JPanel clienteButtonPanel;
    private javax.swing.JPanel clientePanel;
    private javax.swing.JFormattedTextField codigoClienteFormattedTextField;
    private javax.swing.JFormattedTextField codigoVeiculoFormattedTextField;
    private javax.swing.JLabel corLabel;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JCheckBox entradaCheckBox;
    private javax.swing.JFormattedTextField entradaFormattedTextField;
    private javax.swing.JPanel fundoPanel;
    private javax.swing.JLabel kmLabel;
    private javax.swing.JLabel marcaLabel;
    private javax.swing.JLabel modeloLabel;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JComboBox<String> parcelasComboBox;
    private javax.swing.JLabel parcelasLabel;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JLabel salvarButtonLabel;
    private javax.swing.JPanel salvarButtonPanel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel valorLabel;
    private javax.swing.JPanel valorPanel;
    private javax.swing.JLabel veiculoButtonLabel;
    private javax.swing.JPanel veiculoButtonPanel;
    private javax.swing.JPanel veiculoPanel;
    // End of variables declaration//GEN-END:variables
}
