/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatec.aula.view;

import javax.swing.JOptionPane;

/**
 *
 * @author 0040481211026
 */
public class ConversorDeTemperatura extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJFrame
     */
    public ConversorDeTemperatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempButtonGroup = new javax.swing.ButtonGroup();
        principalJPanel = new javax.swing.JPanel();
        entradaLabel = new javax.swing.JLabel();
        saida1Label = new javax.swing.JLabel();
        saida2Label = new javax.swing.JLabel();
        limparJButton = new javax.swing.JButton();
        calcularJButton = new javax.swing.JButton();
        entradaTextField = new javax.swing.JTextField();
        saida1TextField = new javax.swing.JTextField();
        saida2TextField = new javax.swing.JTextField();
        tempCelsiusRadioButton = new javax.swing.JRadioButton();
        tempKelvinRadioButton = new javax.swing.JRadioButton();
        tempFarenheitRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Temperatura");
        setLocationByPlatform(true);
        setName("Main"); // NOI18N
        setResizable(false);

        principalJPanel.setBackground(new java.awt.Color(44, 62, 80));
        principalJPanel.setName("principalJPanel"); // NOI18N

        entradaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entradaLabel.setForeground(new java.awt.Color(255, 255, 255));
        entradaLabel.setText("TEMPERATURA(Celsius)");

        saida1Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saida1Label.setForeground(new java.awt.Color(255, 255, 255));
        saida1Label.setText("Kelvin");

        saida2Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saida2Label.setForeground(new java.awt.Color(255, 255, 255));
        saida2Label.setText("Farenheit");

        limparJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        limparJButton.setText("Limpar");
        limparJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparJButtonActionPerformed(evt);
            }
        });

        calcularJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calcularJButton.setText("Calcular");
        calcularJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularJButtonActionPerformed(evt);
            }
        });

        entradaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaTextFieldActionPerformed(evt);
            }
        });

        saida1TextField.setEditable(false);
        saida1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saida1TextFieldActionPerformed(evt);
            }
        });

        saida2TextField.setEditable(false);

        tempCelsiusRadioButton.setBackground(new java.awt.Color(44, 62, 80));
        tempButtonGroup.add(tempCelsiusRadioButton);
        tempCelsiusRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tempCelsiusRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        tempCelsiusRadioButton.setSelected(true);
        tempCelsiusRadioButton.setText("Celsius");
        tempCelsiusRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tempCelsiusRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempCelsiusRadioButtonActionPerformed(evt);
            }
        });

        tempKelvinRadioButton.setBackground(new java.awt.Color(44, 62, 80));
        tempButtonGroup.add(tempKelvinRadioButton);
        tempKelvinRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tempKelvinRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        tempKelvinRadioButton.setText("Kelvin");
        tempKelvinRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tempKelvinRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempKelvinRadioButtonActionPerformed(evt);
            }
        });

        tempFarenheitRadioButton.setBackground(new java.awt.Color(44, 62, 80));
        tempButtonGroup.add(tempFarenheitRadioButton);
        tempFarenheitRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tempFarenheitRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        tempFarenheitRadioButton.setText("Farenheit");
        tempFarenheitRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tempFarenheitRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempFarenheitRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout principalJPanelLayout = new javax.swing.GroupLayout(principalJPanel);
        principalJPanel.setLayout(principalJPanelLayout);
        principalJPanelLayout.setHorizontalGroup(
            principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalJPanelLayout.createSequentialGroup()
                        .addComponent(entradaLabel)
                        .addGap(0, 346, Short.MAX_VALUE))
                    .addGroup(principalJPanelLayout.createSequentialGroup()
                        .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaTextField)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalJPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(limparJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calcularJButton))
                            .addGroup(principalJPanelLayout.createSequentialGroup()
                                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saida2Label)
                                    .addComponent(saida1Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saida1TextField)
                                    .addComponent(saida2TextField))))
                        .addContainerGap())))
            .addGroup(principalJPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(tempCelsiusRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tempKelvinRadioButton)
                .addGap(151, 151, 151)
                .addComponent(tempFarenheitRadioButton)
                .addContainerGap())
        );
        principalJPanelLayout.setVerticalGroup(
            principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalJPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempCelsiusRadioButton)
                    .addComponent(tempKelvinRadioButton)
                    .addComponent(tempFarenheitRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(entradaLabel)
                .addGap(33, 33, 33)
                .addComponent(entradaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saida1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saida1Label))
                .addGap(32, 32, 32)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saida2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saida2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limparJButton)
                    .addComponent(calcularJButton))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entradaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaTextFieldActionPerformed

    private void saida1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saida1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saida1TextFieldActionPerformed

    private void calcularJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularJButtonActionPerformed
        double entradaDouble, saida1Double = 0, saida2Double = 0;
        if (entradaTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo vazio, por favor insira um valor");
        } else {
            entradaDouble = Double.parseDouble(entradaTextField.getText());
            if (tempCelsiusRadioButton.isSelected()) {
                //celsius para kelvin
                saida1Double = entradaDouble + 273.15;
                //celsius para farenheit
                saida2Double = ((9 * entradaDouble) / 5) + 32;
            } else if (tempKelvinRadioButton.isSelected()) {
                //kelvin para celsius
                saida1Double = entradaDouble - 273.15;
                //kelvin para fahrenheit
                saida2Double = 1.8 * (entradaDouble-273) + 32;
            } else {    
                //fahrenheit para celcius
                saida1Double = (entradaDouble - 32) / 1.8;
                //fahrenheit para Kelvin
                saida2Double = ((entradaDouble -32) /1.8) +273.15;
            }
            saida2TextField.setText(String.valueOf(saida2Double));
            saida1TextField.setText(String.valueOf(saida1Double));
        }
    }//GEN-LAST:event_calcularJButtonActionPerformed

    private void limparJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparJButtonActionPerformed
        entradaTextField.setText("");
        saida2TextField.setText("");
        saida1TextField.setText("");
    }//GEN-LAST:event_limparJButtonActionPerformed

    private void tempCelsiusRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempCelsiusRadioButtonActionPerformed
        entradaLabel.setText("TEMPERATURA (Celsius)");
        saida1Label.setText("Kelvin");
        saida2Label.setText("Fahrenheit");
        entradaTextField.setText("");
        saida2TextField.setText("");
        saida1TextField.setText("");
    }//GEN-LAST:event_tempCelsiusRadioButtonActionPerformed

    private void tempKelvinRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempKelvinRadioButtonActionPerformed
        entradaLabel.setText("TEMPERATURA (Kelvin)");
        saida1Label.setText("Celsius");
        saida2Label.setText("Fahrenheit");
        entradaTextField.setText("");
        saida2TextField.setText("");
        saida1TextField.setText("");
    }//GEN-LAST:event_tempKelvinRadioButtonActionPerformed

    private void tempFarenheitRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempFarenheitRadioButtonActionPerformed
        entradaLabel.setText("TEMPERATURA (Fahrenheit)");
        saida1Label.setText("Celsius");
        saida2Label.setText("Kelvin");
        entradaTextField.setText("");
        saida2TextField.setText("");
        saida1TextField.setText("");
    }//GEN-LAST:event_tempFarenheitRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorDeTemperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularJButton;
    private javax.swing.JLabel entradaLabel;
    private javax.swing.JTextField entradaTextField;
    private javax.swing.JButton limparJButton;
    private javax.swing.JPanel principalJPanel;
    private javax.swing.JLabel saida1Label;
    private javax.swing.JTextField saida1TextField;
    private javax.swing.JLabel saida2Label;
    private javax.swing.JTextField saida2TextField;
    private javax.swing.ButtonGroup tempButtonGroup;
    private javax.swing.JRadioButton tempCelsiusRadioButton;
    private javax.swing.JRadioButton tempFarenheitRadioButton;
    private javax.swing.JRadioButton tempKelvinRadioButton;
    // End of variables declaration//GEN-END:variables
}
