package br.fatec.aula.view;


import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.OutputStream;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.DatePicker;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Tiago Guerino
 */
public class CadastroClienteFrame extends javax.swing.JFrame {

    /**
     * Creates new form CadastroClienteFrame
     */
    public CadastroClienteFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dadosPessoaiPanel = new javax.swing.JPanel();
        nomeLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        sexoLabel = new javax.swing.JLabel();
        sexoComboBox = new javax.swing.JComboBox<>();
        dataNascimentoLabel = new javax.swing.JLabel();
        dataNascimentoButton = new javax.swing.JButton();
        cpfFormattdTextField = new javax.swing.JFormattedTextField();
        dataNascimentoFormattedTextField = new javax.swing.JFormattedTextField();
        contatoPanel = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        telefoneLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        telefoneComboBox = new javax.swing.JComboBox<>();
        tipoLabel = new javax.swing.JLabel();
        telefoneFormattedTextField = new javax.swing.JFormattedTextField();
        limparButton = new javax.swing.JButton();
        gravarButton = new javax.swing.JButton();
        carregarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Cliente");
        setLocationByPlatform(true);
        setName("Main"); // NOI18N
        setResizable(false);

        dadosPessoaiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        nomeLabel.setText("Nome");

        cpfLabel.setText("CPF");

        nomeTextField.setToolTipText("Nome do cliente");

        sexoLabel.setText("Sexo");

        sexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Feminino", "Masculino" }));
        sexoComboBox.setToolTipText("Sexo do cliente");

        dataNascimentoLabel.setText("Data de nascimento");

        dataNascimentoButton.setText("Selecionar Data");
        dataNascimentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimentoButtonActionPerformed(evt);
            }
        });

        try {
            cpfFormattdTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfFormattdTextField.setToolTipText("CPF do cliente");

        try {
            dataNascimentoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataNascimentoFormattedTextField.setToolTipText("Data de nascimento do cliente");

        javax.swing.GroupLayout dadosPessoaiPanelLayout = new javax.swing.GroupLayout(dadosPessoaiPanel);
        dadosPessoaiPanel.setLayout(dadosPessoaiPanelLayout);
        dadosPessoaiPanelLayout.setHorizontalGroup(
            dadosPessoaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosPessoaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosPessoaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosPessoaiPanelLayout.createSequentialGroup()
                        .addGroup(dadosPessoaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dadosPessoaiPanelLayout.createSequentialGroup()
                                .addComponent(cpfLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(dataNascimentoFormattedTextField)
                            .addComponent(cpfFormattdTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dadosPessoaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosPessoaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosPessoaiPanelLayout.createSequentialGroup()
                                    .addComponent(sexoLabel)
                                    .addGap(128, 128, 128))
                                .addGroup(dadosPessoaiPanelLayout.createSequentialGroup()
                                    .addComponent(sexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap()))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosPessoaiPanelLayout.createSequentialGroup()
                                .addComponent(dataNascimentoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(dadosPessoaiPanelLayout.createSequentialGroup()
                        .addComponent(nomeLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dadosPessoaiPanelLayout.createSequentialGroup()
                        .addGroup(dadosPessoaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dadosPessoaiPanelLayout.createSequentialGroup()
                                .addComponent(dataNascimentoLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(nomeTextField))
                        .addContainerGap())))
        );
        dadosPessoaiPanelLayout.setVerticalGroup(
            dadosPessoaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosPessoaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeLabel)
                .addGap(1, 1, 1)
                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosPessoaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpfLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sexoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosPessoaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfFormattdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataNascimentoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dadosPessoaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascimentoButton)
                    .addComponent(dataNascimentoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        contatoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));

        emailLabel.setText("Email");

        telefoneLabel.setText("Telefone");

        emailTextField.setToolTipText("Email do cliente");
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        telefoneComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Telefone Residencial", "Telefone Contato", "Celular Pessoal", "Celular Contato" }));
        telefoneComboBox.setToolTipText("Tipo de telefone do cliente");
        telefoneComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                telefoneComboBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        tipoLabel.setText("Tipo");

        try {
            telefoneFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneFormattedTextField.setToolTipText("Telefone do cliente");

        javax.swing.GroupLayout contatoPanelLayout = new javax.swing.GroupLayout(contatoPanel);
        contatoPanel.setLayout(contatoPanelLayout);
        contatoPanelLayout.setHorizontalGroup(
            contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contatoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contatoPanelLayout.createSequentialGroup()
                        .addComponent(telefoneFormattedTextField)
                        .addGap(18, 18, 18)
                        .addComponent(telefoneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(emailTextField)
                    .addGroup(contatoPanelLayout.createSequentialGroup()
                        .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefoneLabel)
                            .addComponent(emailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tipoLabel)
                        .addGap(130, 130, 130))))
        );
        contatoPanelLayout.setVerticalGroup(
            contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contatoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneLabel)
                    .addComponent(tipoLabel))
                .addGap(6, 6, 6)
                .addGroup(contatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        limparButton.setText("Limpar");
        limparButton.setToolTipText("Limpar informações");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        gravarButton.setText("Gravar");
        gravarButton.setToolTipText("Gravar informações");
        gravarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravarButtonActionPerformed(evt);
            }
        });

        carregarButton.setText("Carregar");
        carregarButton.setToolTipText("Carregar informações");
        carregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dadosPessoaiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contatoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(limparButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carregarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gravarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(dadosPessoaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contatoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limparButton)
                    .addComponent(gravarButton)
                    .addComponent(carregarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void dataNascimentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoButtonActionPerformed
        DatePicker data = new DatePicker();

    }//GEN-LAST:event_dataNascimentoButtonActionPerformed

    private void gravarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravarButtonActionPerformed
        try {
            OutputStream saida = new FileOutputStream("C:\\Users\\Tiago Guerino\\Documents\\NetBeansProjects\\CadastroCliente\\Cliente.txt");
            saida.write(nomeTextField.getText().getBytes());
            saida.write("\r\n".getBytes());
            saida.write(cpfFormattdTextField.getText().getBytes());
            saida.write("\r\n".getBytes());
            saida.write(sexoComboBox.getSelectedItem().toString().getBytes());
            saida.write("\r\n".getBytes());
            saida.write(dataNascimentoFormattedTextField.getText().getBytes());
            saida.write("\r\n".getBytes());
            saida.write(telefoneFormattedTextField.getText().getBytes());
            saida.write("\r\n".getBytes());
            saida.write(telefoneComboBox.getSelectedItem().toString().getBytes());
            saida.write("\r\n".getBytes());
            saida.write(emailTextField.getText().getBytes());
            saida.write("\r\n".getBytes());

            saida.flush();
            saida.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(CadastroClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CadastroClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_gravarButtonActionPerformed

    private void limparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparButtonActionPerformed
        nomeTextField.setText("");
        cpfFormattdTextField.setText("");
        telefoneFormattedTextField.setText("");
        emailTextField.setText("");
        dataNascimentoFormattedTextField.setText("");
        sexoComboBox.setSelectedIndex(0);
        telefoneComboBox.setSelectedIndex(0);

    }//GEN-LAST:event_limparButtonActionPerformed

    private void telefoneComboBoxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_telefoneComboBoxPopupMenuWillBecomeInvisible
        telefoneFormattedTextField.setText("");
        telefoneFormattedTextField.setFormatterFactory(null);
        telefoneFormattedTextField.setValue(null);
        String texto = telefoneComboBox.getSelectedItem().toString();
        try {
            if (texto.contains("Telefone")) {
                MaskFormatter mascara = new MaskFormatter("(##) ####-####");
                DefaultFormatterFactory formato = new DefaultFormatterFactory(mascara);
                telefoneFormattedTextField.setFormatterFactory(formato);
            } else {
                MaskFormatter mascara = new MaskFormatter("(##) 9####-####");
                DefaultFormatterFactory formato = new DefaultFormatterFactory(mascara);
                telefoneFormattedTextField.setFormatterFactory(formato);
            }
        } catch (ParseException ex) {

        }

    }//GEN-LAST:event_telefoneComboBoxPopupMenuWillBecomeInvisible

    private void carregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarButtonActionPerformed
        try {
            FileReader leitor = new FileReader("C:\\Users\\Tiago Guerino\\Documents\\NetBeansProjects\\CadastroCliente\\Cliente.txt");
            BufferedReader buffer = new BufferedReader(leitor);
            
            String nome=buffer.readLine();
            String cpf=buffer.readLine();
            String sexo=buffer.readLine();
            String dataNascimento=buffer.readLine();
            String telefone=buffer.readLine();
            String tipoTelefone=buffer.readLine();
            String email=buffer.readLine();
            
            nomeTextField.setText(nome);
            cpfFormattdTextField.setText(cpf);
            dataNascimentoFormattedTextField.setText(dataNascimento);
            telefoneFormattedTextField.setText(telefone);
            emailTextField.setText(email);
            sexoComboBox.setSelectedItem(sexo);
            telefoneComboBox.setSelectedItem(tipoTelefone);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CadastroClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CadastroClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_carregarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClienteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carregarButton;
    private javax.swing.JPanel contatoPanel;
    private javax.swing.JFormattedTextField cpfFormattdTextField;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JPanel dadosPessoaiPanel;
    private javax.swing.JButton dataNascimentoButton;
    private javax.swing.JFormattedTextField dataNascimentoFormattedTextField;
    private javax.swing.JLabel dataNascimentoLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton gravarButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limparButton;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JComboBox<String> sexoComboBox;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JComboBox<String> telefoneComboBox;
    private javax.swing.JFormattedTextField telefoneFormattedTextField;
    private javax.swing.JLabel telefoneLabel;
    private javax.swing.JLabel tipoLabel;
    // End of variables declaration//GEN-END:variables
}
