package br.edu.fatec.aula.model;
// Generated 18/10/2017 16:45:56 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private String nome;
     private String senha;

    public Usuario() {
    }

	
    public Usuario(int id) {
        this.id = id;
    }
    public Usuario(int id, String nome, String senha) {
       this.id = id;
       this.nome = nome;
       this.senha = senha;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


