/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatec.monitoria.view;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Tiago Guerino
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseButtonGroup = new javax.swing.ButtonGroup();
        convertidoButtonGroup = new javax.swing.ButtonGroup();
        principalPanel = new javax.swing.JPanel();
        valorLabel = new javax.swing.JLabel();
        valorFormattedTextField = new javax.swing.JFormattedTextField();
        realBaseRadioButton = new javax.swing.JRadioButton();
        euroBaseRadioButton = new javax.swing.JRadioButton();
        dolarBaseRadioButton = new javax.swing.JRadioButton();
        euroConvertidoRadioButton = new javax.swing.JRadioButton();
        dolarConvertidoRadioButton = new javax.swing.JRadioButton();
        realConvertidoRadioButton = new javax.swing.JRadioButton();
        limparButton = new javax.swing.JButton();
        calcularButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de moedas");

        valorLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valorLabel.setText("Valor");

        valorFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        baseButtonGroup.add(realBaseRadioButton);
        realBaseRadioButton.setSelected(true);
        realBaseRadioButton.setText("Real");

        baseButtonGroup.add(euroBaseRadioButton);
        euroBaseRadioButton.setText("Euro");

        baseButtonGroup.add(dolarBaseRadioButton);
        dolarBaseRadioButton.setText("Dólar");

        convertidoButtonGroup.add(euroConvertidoRadioButton);
        euroConvertidoRadioButton.setText("Euro");

        convertidoButtonGroup.add(dolarConvertidoRadioButton);
        dolarConvertidoRadioButton.setSelected(true);
        dolarConvertidoRadioButton.setText("Dólar");

        convertidoButtonGroup.add(realConvertidoRadioButton);
        realConvertidoRadioButton.setText("Real");

        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        calcularButton.setText("Calcular");
        calcularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout principalPanelLayout = new javax.swing.GroupLayout(principalPanel);
        principalPanel.setLayout(principalPanelLayout);
        principalPanelLayout.setHorizontalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, principalPanelLayout.createSequentialGroup()
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorFormattedTextField)
                            .addGroup(principalPanelLayout.createSequentialGroup()
                                .addComponent(valorLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, principalPanelLayout.createSequentialGroup()
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(euroBaseRadioButton)
                            .addComponent(realBaseRadioButton)
                            .addComponent(dolarBaseRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(euroConvertidoRadioButton)
                            .addComponent(realConvertidoRadioButton)
                            .addComponent(dolarConvertidoRadioButton))
                        .addGap(96, 96, 96))
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addComponent(calcularButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(limparButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        principalPanelLayout.setVerticalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(valorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addComponent(realBaseRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(dolarBaseRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(euroBaseRadioButton))
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addComponent(realConvertidoRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(dolarConvertidoRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(euroConvertidoRadioButton)))
                .addGap(28, 28, 28)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limparButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcularButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void limparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparButtonActionPerformed
        valorFormattedTextField.setValue(null);
        realBaseRadioButton.setSelected(true);
        dolarConvertidoRadioButton.setSelected(true);
    }//GEN-LAST:event_limparButtonActionPerformed

    private void calcularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularButtonActionPerformed
        DecimalFormat formato = new DecimalFormat("#0.00");

        if (valorFormattedTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor insira um valor","Erro",0);
        } else {

            double valor, resultado;
            String valorEx = valorFormattedTextField.getText();
            String valorStg = valorFormattedTextField.getText().replace(',', '.');
            String resultadoStg;
            valor = Double.parseDouble(valorStg);

            if (realBaseRadioButton.isSelected() && dolarConvertidoRadioButton.isSelected()) {
                resultado = valor / 3.067;
                resultadoStg = String.valueOf(formato.format(resultado));
                JOptionPane.showMessageDialog(this, "R$" + valorEx + " convertidos para dólar são US$" + resultadoStg,"Resultado",1);
            } else if (dolarBaseRadioButton.isSelected() && realConvertidoRadioButton.isSelected()) {
                resultado = valor * 3.067;
                resultadoStg = String.valueOf(formato.format(resultado));
                JOptionPane.showMessageDialog(this, "US$" + valorEx + " convertidos para real são R$" + resultadoStg,"Resultado",1);
            } else if ((dolarBaseRadioButton.isSelected() && dolarConvertidoRadioButton.isSelected())
                    || (realBaseRadioButton.isSelected() && realConvertidoRadioButton.isSelected())
                    || (euroBaseRadioButton.isSelected() && euroConvertidoRadioButton.isSelected())) {
                JOptionPane.showMessageDialog(this, "Escolha moedas diferentes","Erro",0);
            } else if (dolarBaseRadioButton.isSelected() && euroConvertidoRadioButton.isSelected()) {
                resultado = valor * 0.80909;
                resultadoStg = String.valueOf(formato.format(resultado));
                JOptionPane.showMessageDialog(this, "US$" + valorEx + " convertidos para euro são €" + resultadoStg,"Resultado",1);
            } else if (euroBaseRadioButton.isSelected() && realConvertidoRadioButton.isSelected()) {
                resultado = valor / 0.24818;
                resultadoStg = String.valueOf(formato.format(resultado));
                JOptionPane.showMessageDialog(this, "€" + valorEx + " convertidos para real são R$" + resultadoStg,"Resultado",1);
            } else if (euroBaseRadioButton.isSelected() && dolarConvertidoRadioButton.isSelected()) {
                resultado = valor / 0.80909;
                resultadoStg = String.valueOf(formato.format(resultado));
                JOptionPane.showMessageDialog(this, "€" + valorEx + " convertidos para real são R$" + resultadoStg,"Resultado",1);
            } else if (realBaseRadioButton.isSelected() && euroConvertidoRadioButton.isSelected()) {
                resultado = valor * 0.24818;
                resultadoStg = String.valueOf(formato.format(resultado));
                JOptionPane.showMessageDialog(this, "R$" + valorEx + " convertidos para euro são €" + resultadoStg,"Resultado",1);
            }

        }

    }//GEN-LAST:event_calcularButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup baseButtonGroup;
    private javax.swing.JButton calcularButton;
    private javax.swing.ButtonGroup convertidoButtonGroup;
    private javax.swing.JRadioButton dolarBaseRadioButton;
    private javax.swing.JRadioButton dolarConvertidoRadioButton;
    private javax.swing.JRadioButton euroBaseRadioButton;
    private javax.swing.JRadioButton euroConvertidoRadioButton;
    private javax.swing.JButton limparButton;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JRadioButton realBaseRadioButton;
    private javax.swing.JRadioButton realConvertidoRadioButton;
    private javax.swing.JFormattedTextField valorFormattedTextField;
    private javax.swing.JLabel valorLabel;
    // End of variables declaration//GEN-END:variables
}
