package br.edu.fatec.aula.model;
// Generated 02/12/2017 18:07:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Carros generated by hbm2java
 */
@Entity
@Table(name = "carros")
public class Carros implements java.io.Serializable {

    @Id
    @GeneratedValue(generator = "increment")
    @GenericGenerator(name = "increment", strategy = "increment")
    private Integer idcarros;
    private String modelo;
    private String ano;
    private String marca;
    private String tipo;
    private String combustivel;
    private String cilindradas;
    private String cor;
    private Double valor;
    private String opcional;
    private String km;
    @ManyToOne
    @JoinTable(name="venda")
    @JoinColumn
    private Set vendas = new HashSet(0);
    private String parametro;

    public Carros() {
    }

    public Carros(String modelo, String ano, String marca, String tipo, String combustivel, String cilindradas, String cor, Double valor, String opcional, String km, Set vendas) {
        this.modelo = modelo;
        this.ano = ano;
        this.marca = marca;
        this.tipo = tipo;
        this.combustivel = combustivel;
        this.cilindradas = cilindradas;
        this.cor = cor;
        this.valor = valor;
        this.opcional = opcional;
        this.km = km;
        this.vendas = vendas;
        this.parametro=parametro;
    }

    public Integer getIdcarros() {
        return this.idcarros;
    }

    public void setIdcarros(Integer idcarros) {
        this.idcarros = idcarros;
    }

    public String getModelo() {
        return this.modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public String getAno() {
        return this.ano;
    }

    public void setAno(String ano) {
        this.ano = ano;
    }

    public String getMarca() {
        return this.marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getCombustivel() {
        return this.combustivel;
    }

    public void setCombustivel(String combustivel) {
        this.combustivel = combustivel;
    }

    public String getCilindradas() {
        return this.cilindradas;
    }

    public void setCilindradas(String cilindradas) {
        this.cilindradas = cilindradas;
    }

    public String getCor() {
        return this.cor;
    }

    public void setCor(String cor) {
        this.cor = cor;
    }

    public Double getValor() {
        return this.valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

    public String getOpcional() {
        return this.opcional;
    }

    public void setOpcional(String opcional) {
        this.opcional = opcional;
    }

    public String getKm() {
        return this.km;
    }

    public void setKm(String km) {
        this.km = km;
    }

    public Set getVendas() {
        return this.vendas;
    }

    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }
    
    public String getParametro(){
        return this.parametro;
    }
    
    public void setParametro(String parametro){
        this.parametro=parametro;
    }
}
