package br.edu.fatec.aula.model;
// Generated 02/12/2017 18:07:21 by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer idlogin;
     private String usuario;
     private String senha;

    public Login() {
    }

    public Login(String usuario, String senha) {
       this.usuario = usuario;
       this.senha = senha;
    }
   
    public Integer getIdlogin() {
        return this.idlogin;
    }
    
    public void setIdlogin(Integer idlogin) {
        this.idlogin = idlogin;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


