package br.edu.fatec.aula.model;
// Generated 02/12/2017 18:07:21 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Venda generated by hbm2java
 */
@Entity
@Table(name = "venda")
public class Venda implements java.io.Serializable {

    @Id
    @GeneratedValue(generator = "increment")
    @GenericGenerator(name = "increment", strategy = "increment")

    @OneToOne(mappedBy = "venda")
    VendaId id;
    @ManyToOne
    private Carros carros;
    @ManyToOne
    private Clientes clientes;
    private Double entrada;
    private Integer parcelas;
    private Double total;

    public Venda() {
    }

    public Venda(VendaId id, Carros carros, Clientes clientes) {
        this.id = id;
        this.carros = carros;
        this.clientes = clientes;
    }

    public Venda(VendaId id, Carros carros, Clientes clientes, Double entrada, Integer parcelas) {
        this.id = id;
        this.carros = carros;
        this.clientes = clientes;
        this.entrada = entrada;
        this.parcelas = parcelas;
    }

    public VendaId getId() {
        return this.id;
    }

    public void setId(VendaId id) {
        this.id = id;
    }

    public Carros getCarros() {
        return this.carros;
    }

    public void setCarros(Carros carros) {
        this.carros = carros;
    }

    public Clientes getClientes() {
        return this.clientes;
    }

    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

    public Double getEntrada() {
        return this.entrada;
    }

    public void setEntrada(Double entrada) {
        this.entrada = entrada;
    }

    public Integer getParcelas() {
        return this.parcelas;
    }

    public void setParcelas(Integer parcelas) {
        this.parcelas = parcelas;
    }

    public Double getTotal() {
        return this.entrada;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

}
