/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatec.aula.view;

import java.awt.Image;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tiago Guerino
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoButtonGroup = new javax.swing.ButtonGroup();
        principalPanel = new javax.swing.JPanel();
        novoButton = new javax.swing.JButton();
        femininoRadioButton = new javax.swing.JRadioButton();
        editarButton = new javax.swing.JButton();
        excluirButton = new javax.swing.JButton();
        maisButton = new javax.swing.JButton();
        gerarButton = new javax.swing.JButton();
        nomeLabel = new javax.swing.JLabel();
        sexoLabel = new javax.swing.JLabel();
        rgLabel = new javax.swing.JLabel();
        telefoneLabel = new javax.swing.JLabel();
        celularLabel = new javax.swing.JLabel();
        enderecoLabel = new javax.swing.JLabel();
        bairroLabel = new javax.swing.JLabel();
        cidadeLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        obsLabel = new javax.swing.JLabel();
        masculinoRadioButton = new javax.swing.JRadioButton();
        nomeTextField = new javax.swing.JTextField();
        enderecoTextField = new javax.swing.JTextField();
        bairroTextField = new javax.swing.JTextField();
        cidadeTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        rgFormattedTextField = new javax.swing.JFormattedTextField();
        telefoneFormattedTextField = new javax.swing.JFormattedTextField();
        celularFormattedTextField = new javax.swing.JFormattedTextField();
        estadoLabel = new javax.swing.JLabel();
        estadoComboBox = new javax.swing.JComboBox<>();
        imgLabel = new javax.swing.JLabel();
        menosButton = new javax.swing.JButton();
        cpfLabel = new javax.swing.JLabel();
        cpfFormattedTextField = new javax.swing.JFormattedTextField();
        cepLabel = new javax.swing.JLabel();
        obsScrollPane = new javax.swing.JScrollPane();
        obsTextPane = new javax.swing.JTextPane();
        cepFormattedTextField = new javax.swing.JFormattedTextField();
        tabelaScrollPane = new javax.swing.JScrollPane();
        cadastroTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Cliente");
        setResizable(false);

        principalPanel.setBackground(new java.awt.Color(106, 185, 172));

        novoButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        novoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/aula/view/if_window-new_118802 (1).png"))); // NOI18N
        novoButton.setText("Novo");
        novoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoButtonActionPerformed(evt);
            }
        });

        femininoRadioButton.setBackground(new java.awt.Color(106, 185, 172));
        sexoButtonGroup.add(femininoRadioButton);
        femininoRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        femininoRadioButton.setForeground(new java.awt.Color(51, 51, 51));
        femininoRadioButton.setSelected(true);
        femininoRadioButton.setText("Feminino");

        editarButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/aula/view/if_edit_173002.png"))); // NOI18N
        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        excluirButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        excluirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/aula/view/if_edit-delete_118920.png"))); // NOI18N
        excluirButton.setText("Excluir");
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        maisButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maisButton.setText("+");
        maisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisButtonActionPerformed(evt);
            }
        });

        gerarButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gerarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/aula/view/if_save_173091.png"))); // NOI18N
        gerarButton.setText("Gerar Contrato");
        gerarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarButtonActionPerformed(evt);
            }
        });

        nomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(51, 51, 51));
        nomeLabel.setText("Nome");

        sexoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sexoLabel.setForeground(new java.awt.Color(51, 51, 51));
        sexoLabel.setText("Sexo");

        rgLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rgLabel.setForeground(new java.awt.Color(51, 51, 51));
        rgLabel.setText("RG");

        telefoneLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telefoneLabel.setForeground(new java.awt.Color(51, 51, 51));
        telefoneLabel.setText("Telefone");

        celularLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        celularLabel.setForeground(new java.awt.Color(51, 51, 51));
        celularLabel.setText("Celular");

        enderecoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enderecoLabel.setForeground(new java.awt.Color(51, 51, 51));
        enderecoLabel.setText("Endereço");

        bairroLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bairroLabel.setForeground(new java.awt.Color(51, 51, 51));
        bairroLabel.setText("Bairro");

        cidadeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cidadeLabel.setForeground(new java.awt.Color(51, 51, 51));
        cidadeLabel.setText("Cidade");

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(51, 51, 51));
        emailLabel.setText("Email");

        obsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        obsLabel.setForeground(new java.awt.Color(51, 51, 51));
        obsLabel.setText("Observação");

        masculinoRadioButton.setBackground(new java.awt.Color(106, 185, 172));
        sexoButtonGroup.add(masculinoRadioButton);
        masculinoRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        masculinoRadioButton.setForeground(new java.awt.Color(51, 51, 51));
        masculinoRadioButton.setText("Masculino");

        nomeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        enderecoTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        bairroTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cidadeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        emailTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        rgFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        rgFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            telefoneFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            celularFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        celularFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        estadoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        estadoLabel.setForeground(new java.awt.Color(51, 51, 51));
        estadoLabel.setText("Estado");

        estadoComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        estadoComboBox.setForeground(new java.awt.Color(51, 51, 51));
        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        imgLabel.setForeground(new java.awt.Color(51, 51, 51));

        menosButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menosButton.setText("-");
        menosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosButtonActionPerformed(evt);
            }
        });

        cpfLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpfLabel.setForeground(new java.awt.Color(51, 51, 51));
        cpfLabel.setText("CPF");

        try {
            cpfFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cepLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cepLabel.setForeground(new java.awt.Color(51, 51, 51));
        cepLabel.setText("CEP");

        obsTextPane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        obsScrollPane.setViewportView(obsTextPane);

        try {
            cepFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cepFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout principalPanelLayout = new javax.swing.GroupLayout(principalPanel);
        principalPanel.setLayout(principalPanelLayout);
        principalPanelLayout.setHorizontalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createSequentialGroup()
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, principalPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(novoButton)
                        .addGap(18, 18, 18)
                        .addComponent(editarButton)
                        .addGap(18, 18, 18)
                        .addComponent(excluirButton)
                        .addGap(18, 18, 18)
                        .addComponent(gerarButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, principalPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(obsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(obsScrollPane))
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(principalPanelLayout.createSequentialGroup()
                                .addComponent(maisButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addComponent(menosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(principalPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createSequentialGroup()
                                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cidadeLabel)
                                    .addComponent(emailLabel))
                                .addGap(18, 18, 18)
                                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailTextField)
                                    .addGroup(principalPanelLayout.createSequentialGroup()
                                        .addComponent(cidadeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                                        .addGap(22, 22, 22)
                                        .addComponent(estadoLabel)
                                        .addGap(12, 12, 12)
                                        .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(principalPanelLayout.createSequentialGroup()
                                .addComponent(bairroLabel)
                                .addGap(23, 23, 23)
                                .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cepLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cepFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(principalPanelLayout.createSequentialGroup()
                                .addComponent(enderecoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sexoLabel)
                            .addGroup(principalPanelLayout.createSequentialGroup()
                                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telefoneLabel)
                                    .addComponent(rgLabel)
                                    .addComponent(nomeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(principalPanelLayout.createSequentialGroup()
                                            .addComponent(telefoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(91, 91, 91)
                                            .addComponent(celularLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(celularFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(principalPanelLayout.createSequentialGroup()
                                            .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(principalPanelLayout.createSequentialGroup()
                                                    .addComponent(femininoRadioButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(masculinoRadioButton))
                                                .addGroup(principalPanelLayout.createSequentialGroup()
                                                    .addComponent(rgFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(cpfLabel)))
                                            .addGap(18, 18, 18)
                                            .addComponent(cpfFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(20, 20, 20))
        );
        principalPanelLayout.setVerticalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoButton)
                    .addComponent(editarButton)
                    .addComponent(excluirButton)
                    .addComponent(gerarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeLabel)
                            .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(femininoRadioButton)
                                .addComponent(masculinoRadioButton)))
                        .addGap(18, 18, 18)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rgLabel)
                            .addComponent(rgFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfLabel))
                        .addGap(18, 18, 18)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefoneLabel)
                            .addComponent(telefoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(celularLabel)
                            .addComponent(celularFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enderecoTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cepLabel)
                                .addComponent(cepFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bairroLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cidadeLabel)
                            .addComponent(estadoLabel)
                            .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel)))
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menosButton)
                            .addComponent(maisButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createSequentialGroup()
                        .addComponent(obsLabel)
                        .addGap(52, 52, 52)))
                .addContainerGap())
        );

        cadastroTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sexo", "RG", "CPF", "Telefone", "Celular", "Endereço", "Bairro", "Estado", "Cidade", "CEP", "Email", "Obs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cadastroTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        cadastroTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroTableMouseClicked(evt);
            }
        });
        tabelaScrollPane.setViewportView(cadastroTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(principalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabelaScrollPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void maisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisButtonActionPerformed

        JFileChooser escolha = new JFileChooser();
        escolha.setDialogTitle("Procurar foto");
        escolha.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Fotos", "jpg", "png");
        escolha.setFileFilter(filtro);

        int resposta = escolha.showOpenDialog(this);

        if (resposta == JFileChooser.APPROVE_OPTION) {
            File file = escolha.getSelectedFile();
            ImageIcon icone = new ImageIcon(file.getPath());
            Image imagem = icone.getImage();
            Image novoicone = imagem.getScaledInstance(177, 145,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
            icone = new ImageIcon(novoicone);
            imgLabel.setIcon(icone);

        }

    }//GEN-LAST:event_maisButtonActionPerformed

    private void menosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosButtonActionPerformed
        imgLabel.setIcon(null);
    }//GEN-LAST:event_menosButtonActionPerformed

    private void novoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoButtonActionPerformed
       
        String nome = nomeTextField.getText();
        String sexo;
        if (masculinoRadioButton.isSelected()) {

            sexo = "Masculino";

        } else {
            sexo = "Feminino";
        }
        String rg = rgFormattedTextField.getText();
        String cpf = cpfFormattedTextField.getText();
        String telefone = telefoneFormattedTextField.getText();
        String celular = celularFormattedTextField.getText();
        String endereco = enderecoTextField.getText();
        String bairro = bairroTextField.getText();
        String estado = (String) estadoComboBox.getSelectedItem();
        String cidade = cidadeTextField.getText();
        String cep = cepFormattedTextField.getText();
        String email = emailTextField.getText();
        String obs = obsTextPane.getText();

        DefaultTableModel tabela;
        tabela = (DefaultTableModel) cadastroTable.getModel();
        Object[] linha = {
            nome,
            sexo,
            rg,
            cpf,
            telefone,
            celular,
            endereco,
            bairro,
            estado,
            cidade,
            cep,
            email,
            obs
        };
        tabela.addRow(linha);

        nomeTextField.setText("");
        rgFormattedTextField.setText("");
        cpfFormattedTextField.setText("");
        enderecoTextField.setText("");
        cidadeTextField.setText("");
        bairroTextField.setText("");
        estadoComboBox.setSelectedIndex(0);
        femininoRadioButton.setSelected(true);
        cepFormattedTextField.setText("");
        emailTextField.setText("");
        celularFormattedTextField.setText("");
        obsTextPane.setText("");
        telefoneFormattedTextField.setText("");
       

    }//GEN-LAST:event_novoButtonActionPerformed

    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed
        int linhaSelecionada = cadastroTable.getSelectedRow();

        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha da tabela");
            return;
        }
        DefaultTableModel tabela;
        tabela = (DefaultTableModel) cadastroTable.getModel();
        tabela.removeRow(linhaSelecionada);
    }//GEN-LAST:event_excluirButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        int linhaSelecionada = cadastroTable.getSelectedRow();
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha da tabela");
            return;

        }

        String nome = nomeTextField.getText();
        String sexo;
        if (masculinoRadioButton.isSelected()) {

            sexo = "Masculino";

        } else {
            sexo = "Feminino";
        }
        String rg = rgFormattedTextField.getText();
        String cpf = cpfFormattedTextField.getText();
        String telefone = telefoneFormattedTextField.getText();
        String celular = celularFormattedTextField.getText();
        String endereco = enderecoTextField.getText();
        String bairro = bairroTextField.getText();
        String estado = (String) estadoComboBox.getSelectedItem();
        String cidade = cidadeTextField.getText();
        String cep = cepFormattedTextField.getText();
        String email = emailTextField.getText();
        String obs = obsTextPane.getText();

        DefaultTableModel tabela;
        tabela = (DefaultTableModel) cadastroTable.getModel();

        tabela.setValueAt(nome, linhaSelecionada, 0);
        tabela.setValueAt(sexo, linhaSelecionada, 1);
        tabela.setValueAt(rg, linhaSelecionada, 2);
        tabela.setValueAt(cpf, linhaSelecionada, 3);
        tabela.setValueAt(telefone, linhaSelecionada, 4);
        tabela.setValueAt(celular, linhaSelecionada, 5);
        tabela.setValueAt(endereco, linhaSelecionada, 6);
        tabela.setValueAt(bairro, linhaSelecionada, 7);
        tabela.setValueAt(estado, linhaSelecionada, 8);
        tabela.setValueAt(cidade, linhaSelecionada, 9);
        tabela.setValueAt(cep, linhaSelecionada, 10);
        tabela.setValueAt(email, linhaSelecionada, 11);
        tabela.setValueAt(obs, linhaSelecionada, 12);

    }//GEN-LAST:event_editarButtonActionPerformed

    private void cadastroTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroTableMouseClicked
        int linhaSelecionada = cadastroTable.getSelectedRow();
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha");
            return;
        }
        DefaultTableModel tabela;
        tabela = (DefaultTableModel) cadastroTable.getModel();

        Object nomeObj = tabela.getValueAt(linhaSelecionada, 0);
        Object sexoObj = tabela.getValueAt(linhaSelecionada, 1);
        Object rgObj = tabela.getValueAt(linhaSelecionada, 2);
        Object cpfObj = tabela.getValueAt(linhaSelecionada, 3);
        Object telefoneObj = tabela.getValueAt(linhaSelecionada, 4);
        Object celularObj = tabela.getValueAt(linhaSelecionada, 5);
        Object enderecoObj = tabela.getValueAt(linhaSelecionada, 6);
        Object bairroObj = tabela.getValueAt(linhaSelecionada, 7);
        Object estadoObj = tabela.getValueAt(linhaSelecionada, 8);
        Object cidadeObj = tabela.getValueAt(linhaSelecionada, 9);
        Object cepObj = tabela.getValueAt(linhaSelecionada, 10);
        Object emailObj = tabela.getValueAt(linhaSelecionada, 11);
        Object obsObj = tabela.getValueAt(linhaSelecionada, 12);

        nomeTextField.setText(String.valueOf(nomeObj));
        rgFormattedTextField.setText(String.valueOf(rgObj));
        cpfFormattedTextField.setText(String.valueOf(cpfObj));
        enderecoTextField.setText(String.valueOf(enderecoObj));
        cidadeTextField.setText(String.valueOf(cidadeObj));
        bairroTextField.setText(String.valueOf(bairroObj));
        cepFormattedTextField.setText(String.valueOf(cepObj));
        emailTextField.setText(String.valueOf(emailObj));
        celularFormattedTextField.setText(String.valueOf(celularObj));
        obsTextPane.setText(String.valueOf(obsObj));
        telefoneFormattedTextField.setText(String.valueOf(telefoneObj));
        estadoComboBox.setSelectedItem(estadoObj);

        if (sexoObj == "Feminino") {
            femininoRadioButton.setSelected(true);
        } else {
            masculinoRadioButton.setSelected(true);
        }

    }//GEN-LAST:event_cadastroTableMouseClicked

    private void gerarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarButtonActionPerformed
        try {
            File arquivo = new File("Contrato - " + nomeTextField.getText() + ".doc");
            FileWriter escritor = new FileWriter(arquivo);
            BufferedWriter buffer = new BufferedWriter(escritor);

            buffer.append("Contrato de Serviço \n\n");
            buffer.append("Eu ");
            buffer.append(nomeTextField.getText());
            buffer.append(", portador do CPF ");
            buffer.append(cpfFormattedTextField.getText());
            buffer.append(", e do RG ");
            buffer.append(rgFormattedTextField.getText());
            buffer.append(" residente no endereço ");
            buffer.append(enderecoTextField.getText());
            buffer.append(" CEP ");
            buffer.append(cepFormattedTextField.getText());
            buffer.append(" bairro ");
            buffer.append(bairroTextField.getText());
            buffer.append(" na cidade ");
            buffer.append(cidadeTextField.getText());
            buffer.append("/");
            buffer.append((String) estadoComboBox.getSelectedItem());
            buffer.append(" estou ciente dos serviços que irei prestar com as observações");
            buffer.append(obsTextPane.getText());
            
            for (int i = 0; i < nomeTextField.getText().length(); i++) {
                 buffer.append("_");
            }

            buffer.append("\n\n");
            buffer.append(nomeTextField.getText());
            buffer.append("\n");
            buffer.append(telefoneFormattedTextField.getText());
            buffer.append("\n");
            buffer.append(emailTextField.getText());
            buffer.append("\n");
            buffer.append(celularFormattedTextField.getText());
            buffer.append("\n");
            
            
            

            buffer.close();
            escritor.close();

        } catch (IOException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gerarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JTextField bairroTextField;
    private javax.swing.JTable cadastroTable;
    private javax.swing.JFormattedTextField celularFormattedTextField;
    private javax.swing.JLabel celularLabel;
    private javax.swing.JFormattedTextField cepFormattedTextField;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JTextField cidadeTextField;
    private javax.swing.JFormattedTextField cpfFormattedTextField;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JButton editarButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JTextField enderecoTextField;
    private javax.swing.JComboBox<String> estadoComboBox;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JButton excluirButton;
    private javax.swing.JRadioButton femininoRadioButton;
    private javax.swing.JButton gerarButton;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JButton maisButton;
    private javax.swing.JRadioButton masculinoRadioButton;
    private javax.swing.JButton menosButton;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JButton novoButton;
    private javax.swing.JLabel obsLabel;
    private javax.swing.JScrollPane obsScrollPane;
    private javax.swing.JTextPane obsTextPane;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JFormattedTextField rgFormattedTextField;
    private javax.swing.JLabel rgLabel;
    private javax.swing.ButtonGroup sexoButtonGroup;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JScrollPane tabelaScrollPane;
    private javax.swing.JFormattedTextField telefoneFormattedTextField;
    private javax.swing.JLabel telefoneLabel;
    // End of variables declaration//GEN-END:variables
}